/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import BUS.DonHang_BUS;
import BUS.KhachHang_BUS;
import BUS.NhanVien_BUS;
import DTO.DonHang_DTO;
import DTO.KhachHang_DTO;
import DTO.NhanVien_DTO;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author datsu
 */
public class JF_Bill extends javax.swing.JFrame {

    /**
     * Creates new form JF_Customer
     */
    DefaultTableModel defaultTableModel;
    DonHang_BUS dh_BUS;
    NhanVien_BUS nv_BUS;
    KhachHang_BUS kh_BUS;
    List<NhanVien_DTO> list_NV;
    List<KhachHang_DTO> list_KH;
    
    SimpleDateFormat dateFormatSQL = new SimpleDateFormat("yyyy/MM/dd");
    
    public JF_Bill() {
        initComponents();
        
        
        JTB_DH.getTableHeader().setFont(new Font("Segoe UI", Font.PLAIN, 15));
        JTB_DH.getTableHeader().setForeground(Color.black);
        JTB_DH.getTableHeader().setPreferredSize(new Dimension(1234, 40));
        
        
        JTB_DH.getColumnModel().getColumn(0).setPreferredWidth(100);
        JTB_DH.getColumnModel().getColumn(0).setMaxWidth(100);
        
        
        defaultTableModel = (DefaultTableModel) JTB_DH.getModel();
        dh_BUS = new DonHang_BUS();
        nv_BUS = new NhanVien_BUS();
        kh_BUS = new KhachHang_BUS();
        list_NV = nv_BUS.getAllStaff();
        list_KH = kh_BUS.getAllCustomer();
        
        LoadTableData(dh_BUS.getAllDonHang());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        JTxt_Header1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        JBTN_SearchDH = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTB_DH = new javax.swing.JTable();
        JBtn_BackHome = new com.k33ptoo.components.KButton();
        JTBN_XemCTDH = new com.k33ptoo.components.KButton();
        JDC_DateSearchDH = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel4.setBackground(new java.awt.Color(255, 153, 0));
        jPanel4.setPreferredSize(new java.awt.Dimension(1329, 93));

        JTxt_Header1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        JTxt_Header1.setForeground(new java.awt.Color(255, 255, 255));
        JTxt_Header1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JTxt_Header1.setText("ĐƠN HÀNG");
        JTxt_Header1.setPreferredSize(new java.awt.Dimension(1236, 93));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JTxt_Header1, javax.swing.GroupLayout.DEFAULT_SIZE, 1234, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(JTxt_Header1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(245, 245, 245));

        JBTN_SearchDH.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JBTN_SearchDH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon_search.png"))); // NOI18N
        JBTN_SearchDH.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JBTN_SearchDH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JBTN_SearchDHMouseClicked(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        JTB_DH.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        JTB_DH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MĐH", "Ngày lập", "Nhân viên", "Khách hàng", "Tổng tiền"
            }
        ));
        JTB_DH.setGridColor(new java.awt.Color(204, 204, 204));
        JTB_DH.setRowHeight(40);
        JTB_DH.setSelectionBackground(new java.awt.Color(153, 153, 153));
        JTB_DH.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        JTB_DH.setShowGrid(false);
        jScrollPane1.setViewportView(JTB_DH);

        JBtn_BackHome.setText("Về trang chủ");
        JBtn_BackHome.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        JBtn_BackHome.setkBackGroundColor(new java.awt.Color(255, 102, 0));
        JBtn_BackHome.setkBorderRadius(30);
        JBtn_BackHome.setkEndColor(new java.awt.Color(51, 153, 255));
        JBtn_BackHome.setkHoverEndColor(new java.awt.Color(51, 102, 255));
        JBtn_BackHome.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        JBtn_BackHome.setkHoverStartColor(new java.awt.Color(51, 102, 255));
        JBtn_BackHome.setkSelectedColor(new java.awt.Color(255, 102, 0));
        JBtn_BackHome.setkStartColor(new java.awt.Color(51, 153, 255));
        JBtn_BackHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtn_BackHomeActionPerformed(evt);
            }
        });

        JTBN_XemCTDH.setText("Xem");
        JTBN_XemCTDH.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        JTBN_XemCTDH.setkBackGroundColor(new java.awt.Color(255, 102, 0));
        JTBN_XemCTDH.setkBorderRadius(30);
        JTBN_XemCTDH.setkEndColor(new java.awt.Color(255, 153, 0));
        JTBN_XemCTDH.setkHoverEndColor(new java.awt.Color(255, 153, 0));
        JTBN_XemCTDH.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        JTBN_XemCTDH.setkHoverStartColor(new java.awt.Color(255, 102, 0));
        JTBN_XemCTDH.setkSelectedColor(new java.awt.Color(255, 102, 0));
        JTBN_XemCTDH.setkStartColor(new java.awt.Color(255, 153, 0));
        JTBN_XemCTDH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTBN_XemCTDHActionPerformed(evt);
            }
        });

        JDC_DateSearchDH.setDateFormatString("dd/MM/yyyy");
        JDC_DateSearchDH.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JDC_DateSearchDH, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JBTN_SearchDH, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JTBN_XemCTDH, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JBtn_BackHome, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JBtn_BackHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JTBN_XemCTDH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JDC_DateSearchDH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JBTN_SearchDH, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 1234, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, "card2");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LoadTableData(List<DonHang_DTO> listDH){ 
        
        defaultTableModel.setRowCount(0);
        String tenNV;
        String tenKH;
        for(DonHang_DTO dh : listDH){
            if(dh.getMaNV() != null){
                tenNV = getNVByMaNV(dh.getMaNV()).getTenNV();
            }
            else{
                tenNV = "Null";
            }
            
            if(dh.getMaKH()!= null){
                tenKH = getKHByMaKH(dh.getMaKH()).getTenKH();
            }
            else{
                tenKH = "Null";
            }
            defaultTableModel.addRow(new Object[] {"DH" + dh.getMaDH(), dh.getNgayLap(), tenNV, tenKH, String.format("%.0f", dh.getTongTien())});
        }
    }
    
    private NhanVien_DTO getNVByMaNV(String manv){
        for(NhanVien_DTO nv : list_NV){
            if(nv.getMaNV().compareTo(manv) == 0){
                return nv;
            }
        }
        return null;
    }
    
    private KhachHang_DTO getKHByMaKH(String makh){
        for(KhachHang_DTO kh : list_KH){
            if(kh.getMaKH().compareTo(makh) == 0){
                return kh;
            }
        }
        return null;
    }
    
    private void JBtn_BackHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtn_BackHomeActionPerformed
        JF_Home jF_Home = new JF_Home();
        jF_Home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_JBtn_BackHomeActionPerformed

    private void JTBN_XemCTDHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTBN_XemCTDHActionPerformed
        int row = JTB_DH.getSelectedRow();
        if(row >=0){
            String madh = String.valueOf(JTB_DH.getValueAt(row, 0));
            String maDHFormat = madh.substring(2);
            new JF_DetailBill(Integer.parseInt(maDHFormat)).setVisible(true);
        }
        else{
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn đơn hàng", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_JTBN_XemCTDHActionPerformed

    private void JBTN_SearchDHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBTN_SearchDHMouseClicked
        if(JDC_DateSearchDH.getDate() != null){
           String ngayNhap = dateFormatSQL.format(JDC_DateSearchDH.getDate());
           LoadTableData(dh_BUS.listSearchDH(ngayNhap));
       }
       else{
           LoadTableData(dh_BUS.getAllDonHang());
       }
    }//GEN-LAST:event_JBTN_SearchDHMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_Bill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JBTN_SearchDH;
    private com.k33ptoo.components.KButton JBtn_BackHome;
    private com.toedter.calendar.JDateChooser JDC_DateSearchDH;
    private com.k33ptoo.components.KButton JTBN_XemCTDH;
    private javax.swing.JTable JTB_DH;
    private javax.swing.JLabel JTxt_Header1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
