/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import BUS.KhachHang_BUS;
import DTO.KhachHang_DTO;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author datsu
 */
public class JF_Customer extends javax.swing.JFrame {

    /**
     * Creates new form JF_Customer
     */
    
    DefaultTableModel defaultTableModel;
    KhachHang_BUS customer_BUS;
    
    public JF_Customer() {
        initComponents();
        
        
        JTB_Customer.getTableHeader().setFont(new Font("Segoe UI", Font.PLAIN, 15));
        JTB_Customer.getTableHeader().setForeground(Color.black);
        JTB_Customer.getTableHeader().setPreferredSize(new Dimension(1234, 40));
        
        
        JTB_Customer.getColumnModel().getColumn(0).setPreferredWidth(100);
        JTB_Customer.getColumnModel().getColumn(0).setMaxWidth(100);
        
        defaultTableModel = (DefaultTableModel) JTB_Customer.getModel();
        customer_BUS = new KhachHang_BUS();
        
        
        LoadTableData();
        EventSelectRow();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        JTxt_Header1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        JTF_TenKH = new GUI.JTextFieldCustom();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JTF_SDTKH = new GUI.JTextFieldCustom();
        jLabel3 = new javax.swing.JLabel();
        JTF_DiaChiKh = new GUI.JTextFieldCustom();
        jLabel4 = new javax.swing.JLabel();
        JTF_EmailKH = new GUI.JTextFieldCustom();
        JTF_MaKH = new GUI.JTextFieldCustom();
        jLabel6 = new javax.swing.JLabel();
        JTF_SearchCustomer = new GUI.JTextFieldCustom();
        jPanel7 = new javax.swing.JPanel();
        JBtn_AddCustomer = new com.k33ptoo.components.KButton();
        JBtn_UpdateCustomer = new com.k33ptoo.components.KButton();
        JBtn_BackHome = new com.k33ptoo.components.KButton();
        JBtn_DeleteCustomer = new com.k33ptoo.components.KButton();
        JBtn_Refresh = new com.k33ptoo.components.KButton();
        JBtn_SearchCustomer = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTB_Customer = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel4.setBackground(new java.awt.Color(255, 153, 0));
        jPanel4.setPreferredSize(new java.awt.Dimension(1329, 93));

        JTxt_Header1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        JTxt_Header1.setForeground(new java.awt.Color(255, 255, 255));
        JTxt_Header1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JTxt_Header1.setText("QUẢN LÝ KHÁCH HÀNG");
        JTxt_Header1.setPreferredSize(new java.awt.Dimension(1236, 93));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JTxt_Header1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(JTxt_Header1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(245, 245, 245));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel1.setText("Tên khách hàng: ");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel2.setText("Số điện thoại:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel3.setText("Địa chỉ:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel4.setText("Email:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel6.setText("Mã KH:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(36, 36, 36)
                        .addComponent(JTF_MaKH, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(31, 31, 31)
                        .addComponent(JTF_DiaChiKh, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JTF_TenKH, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JTF_SDTKH, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(26, 26, 26)
                        .addComponent(JTF_EmailKH, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTF_MaKH, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(36, 36, 36)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTF_TenKH, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(JTF_SDTKH, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTF_DiaChiKh, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(JTF_EmailKH, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(245, 245, 245));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JBtn_AddCustomer.setText("Thêm");
        JBtn_AddCustomer.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        JBtn_AddCustomer.setkBackGroundColor(new java.awt.Color(255, 102, 0));
        JBtn_AddCustomer.setkBorderRadius(30);
        JBtn_AddCustomer.setkEndColor(new java.awt.Color(255, 153, 0));
        JBtn_AddCustomer.setkHoverEndColor(new java.awt.Color(255, 153, 0));
        JBtn_AddCustomer.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        JBtn_AddCustomer.setkHoverStartColor(new java.awt.Color(255, 102, 0));
        JBtn_AddCustomer.setkSelectedColor(new java.awt.Color(255, 102, 0));
        JBtn_AddCustomer.setkStartColor(new java.awt.Color(255, 153, 0));
        JBtn_AddCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtn_AddCustomerActionPerformed(evt);
            }
        });
        jPanel7.add(JBtn_AddCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 160, -1));

        JBtn_UpdateCustomer.setText("Cập nhật");
        JBtn_UpdateCustomer.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        JBtn_UpdateCustomer.setkBackGroundColor(new java.awt.Color(255, 102, 0));
        JBtn_UpdateCustomer.setkBorderRadius(30);
        JBtn_UpdateCustomer.setkEndColor(new java.awt.Color(255, 153, 0));
        JBtn_UpdateCustomer.setkHoverEndColor(new java.awt.Color(255, 153, 0));
        JBtn_UpdateCustomer.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        JBtn_UpdateCustomer.setkHoverStartColor(new java.awt.Color(255, 102, 0));
        JBtn_UpdateCustomer.setkSelectedColor(new java.awt.Color(255, 102, 0));
        JBtn_UpdateCustomer.setkStartColor(new java.awt.Color(255, 153, 0));
        JBtn_UpdateCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtn_UpdateCustomerActionPerformed(evt);
            }
        });
        jPanel7.add(JBtn_UpdateCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 160, -1));

        JBtn_BackHome.setText("Về trang chủ");
        JBtn_BackHome.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        JBtn_BackHome.setkBackGroundColor(new java.awt.Color(255, 102, 0));
        JBtn_BackHome.setkBorderRadius(30);
        JBtn_BackHome.setkEndColor(new java.awt.Color(51, 153, 255));
        JBtn_BackHome.setkHoverEndColor(new java.awt.Color(51, 102, 255));
        JBtn_BackHome.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        JBtn_BackHome.setkHoverStartColor(new java.awt.Color(51, 102, 255));
        JBtn_BackHome.setkSelectedColor(new java.awt.Color(255, 102, 0));
        JBtn_BackHome.setkStartColor(new java.awt.Color(51, 153, 255));
        JBtn_BackHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JBtn_BackHomeMouseClicked(evt);
            }
        });
        JBtn_BackHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtn_BackHomeActionPerformed(evt);
            }
        });
        jPanel7.add(JBtn_BackHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 160, -1));

        JBtn_DeleteCustomer.setText("Xóa");
        JBtn_DeleteCustomer.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        JBtn_DeleteCustomer.setkBackGroundColor(new java.awt.Color(255, 102, 0));
        JBtn_DeleteCustomer.setkBorderRadius(30);
        JBtn_DeleteCustomer.setkEndColor(new java.awt.Color(255, 153, 0));
        JBtn_DeleteCustomer.setkHoverEndColor(new java.awt.Color(255, 153, 0));
        JBtn_DeleteCustomer.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        JBtn_DeleteCustomer.setkHoverStartColor(new java.awt.Color(255, 102, 0));
        JBtn_DeleteCustomer.setkSelectedColor(new java.awt.Color(255, 102, 0));
        JBtn_DeleteCustomer.setkStartColor(new java.awt.Color(255, 153, 0));
        JBtn_DeleteCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtn_DeleteCustomerActionPerformed(evt);
            }
        });
        jPanel7.add(JBtn_DeleteCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 160, -1));

        JBtn_Refresh.setText("Làm mới");
        JBtn_Refresh.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        JBtn_Refresh.setkBackGroundColor(new java.awt.Color(255, 102, 0));
        JBtn_Refresh.setkBorderRadius(30);
        JBtn_Refresh.setkEndColor(new java.awt.Color(255, 153, 0));
        JBtn_Refresh.setkHoverEndColor(new java.awt.Color(255, 153, 0));
        JBtn_Refresh.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        JBtn_Refresh.setkHoverStartColor(new java.awt.Color(255, 102, 0));
        JBtn_Refresh.setkSelectedColor(new java.awt.Color(255, 102, 0));
        JBtn_Refresh.setkStartColor(new java.awt.Color(255, 153, 0));
        JBtn_Refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtn_RefreshActionPerformed(evt);
            }
        });
        jPanel7.add(JBtn_Refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 160, -1));

        JBtn_SearchCustomer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JBtn_SearchCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon_search.png"))); // NOI18N
        JBtn_SearchCustomer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JBtn_SearchCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JBtn_SearchCustomerMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(JTF_SearchCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 1159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JBtn_SearchCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 3, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JTF_SearchCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JBtn_SearchCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new java.awt.CardLayout());

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        JTB_Customer.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        JTB_Customer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MKH", "Tên khách hàng", "Số điện thoại", "Địa chỉ", "Email"
            }
        ));
        JTB_Customer.setGridColor(new java.awt.Color(204, 204, 204));
        JTB_Customer.setRowHeight(40);
        JTB_Customer.setSelectionBackground(new java.awt.Color(153, 153, 153));
        JTB_Customer.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        JTB_Customer.setShowGrid(false);
        jScrollPane1.setViewportView(JTB_Customer);

        jPanel6.add(jScrollPane1, "card2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 1234, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, "card2");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    private void LoadTableData(){ 
        
        defaultTableModel.setRowCount(0);
        List<KhachHang_DTO> listKH = customer_BUS.getAllCustomer();
        for(KhachHang_DTO kh : listKH){
            defaultTableModel.addRow(new Object[] {kh.getMaKH(), kh.getTenKH(), kh.getSdtKH(), kh.getDiaChiKH(), kh.getEmailKH()});
        }
    }
    
    private void EventSelectRow(){
        ListSelectionModel listSelectionModel = JTB_Customer.getSelectionModel();
        listSelectionModel.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                int row = JTB_Customer.getSelectedRow();
                
                if(row >= 0){
                    String maKH = String.valueOf(JTB_Customer.getValueAt(row, 0));
                    String tenKH = String.valueOf(JTB_Customer.getValueAt(row, 1));
                    String sdtKH = String.valueOf(JTB_Customer.getValueAt(row, 2));
                    String diaChiKH = String.valueOf(JTB_Customer.getValueAt(row, 3));
                    String emailKH = String.valueOf(JTB_Customer.getValueAt(row, 4));

                    JTF_MaKH.setText(maKH);
                    JTF_TenKH.setText(tenKH);
                    JTF_SDTKH.setText(sdtKH);
                    JTF_DiaChiKh.setText(diaChiKH);
                    JTF_EmailKH.setText(emailKH);

                    JTF_MaKH.setEnabled(false);
                    JBtn_AddCustomer.setEnabled(false);
                    
                }
           }
        });
    }
    
    private void ClearTextFiled(){
        JTF_MaKH.setText("");
        JTF_TenKH.setText("");
        JTF_SDTKH.setText("");
        JTF_DiaChiKh.setText("");
        JTF_EmailKH.setText("");
    }
    
    private KhachHang_DTO getDataCustomerFromGUI(){
        
        String maKH = JTF_MaKH.getText();
        String tenKH = JTF_TenKH.getText();
        String sdtKH = JTF_SDTKH.getText();
        String diaChiKH = JTF_DiaChiKh.getText();
        String emailKH = JTF_EmailKH.getText();
        
        KhachHang_DTO kh = new KhachHang_DTO();
        kh.setMaKH(maKH);
        kh.setTenKH(tenKH);
        kh.setSdtKH(sdtKH);
        kh.setDiaChiKH(diaChiKH);
        kh.setEmailKH(emailKH);
        
        return kh;
    }
    
    private void JBtn_BackHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtn_BackHomeActionPerformed
        JF_Home jF_Home = new JF_Home();
        jF_Home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_JBtn_BackHomeActionPerformed

    private void JBtn_DeleteCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtn_DeleteCustomerActionPerformed
        int row = JTB_Customer.getSelectedRow();
        
        if(row >= 0){
            int confirm = JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa không?");
        
            if(confirm == JOptionPane.YES_OPTION){
                String maKH = JTF_MaKH.getText();
                customer_BUS.DeleteCustomer(maKH);
                
                LoadTableData();
                JOptionPane.showMessageDialog(this, "Xóa thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                ClearTextFiled();  
            }
        }
        else{
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn khách hàng cần xóa", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_JBtn_DeleteCustomerActionPerformed

    private void JBtn_AddCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtn_AddCustomerActionPerformed
         
        if(JTF_MaKH.getText().compareTo("") != 0 && JTF_TenKH.getText().compareTo("") != 0){
            customer_BUS.AddCustomer(getDataCustomerFromGUI());
            LoadTableData();
            JOptionPane.showMessageDialog(this, "Thêm thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            ClearTextFiled();
        }
        else{
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập thông tin khách hàng", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_JBtn_AddCustomerActionPerformed

    private void JBtn_RefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtn_RefreshActionPerformed
        ClearTextFiled();
        LoadTableData();
        JTF_MaKH.setEnabled(true);
        JBtn_AddCustomer.setEnabled(true);
    }//GEN-LAST:event_JBtn_RefreshActionPerformed

    private void JBtn_UpdateCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtn_UpdateCustomerActionPerformed
       int row = JTB_Customer.getSelectedRow();
            
            if(row >= 0){
                defaultTableModel.setRowCount(0);
                customer_BUS.UpdateCustomer(getDataCustomerFromGUI());
                LoadTableData();
                JOptionPane.showMessageDialog(this, "Sửa thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                ClearTextFiled();
                JTF_MaKH.setEnabled(true);
                JBtn_AddCustomer.setEnabled(true);
            }
            else{
                JOptionPane.showMessageDialog(this, "Bạn chưa chọn khách hàng cần sửa", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            }
    }//GEN-LAST:event_JBtn_UpdateCustomerActionPerformed

    private void JBtn_BackHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBtn_BackHomeMouseClicked
        if(JTF_SearchCustomer.getText().length() > 0){
            String tenKH = JTF_SearchCustomer.getText();
 
            defaultTableModel.setRowCount(0);
            List<KhachHang_DTO> listKH = customer_BUS.SearchCustomer(tenKH);
            for(KhachHang_DTO kh : listKH){
                defaultTableModel.addRow(new Object[] {kh.getMaKH(), kh.getTenKH(), kh.getSdtKH(), kh.getDiaChiKH(), kh.getEmailKH()});
            }
        }
        else{
            LoadTableData();
        }
    }//GEN-LAST:event_JBtn_BackHomeMouseClicked

    private void JBtn_SearchCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBtn_SearchCustomerMouseClicked
        if(JTF_SearchCustomer.getText().length() > 0){
            String tenKH = JTF_SearchCustomer.getText();
 
            defaultTableModel.setRowCount(0);
            List<KhachHang_DTO> listKH = customer_BUS.SearchCustomer(tenKH);
            for(KhachHang_DTO kh : listKH){
                defaultTableModel.addRow(new Object[] {kh.getMaKH(), kh.getTenKH(), kh.getSdtKH(), kh.getDiaChiKH(), kh.getEmailKH()});
            }
        }
        else{
            LoadTableData();
        }
    }//GEN-LAST:event_JBtn_SearchCustomerMouseClicked

   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_Customer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KButton JBtn_AddCustomer;
    private com.k33ptoo.components.KButton JBtn_BackHome;
    private com.k33ptoo.components.KButton JBtn_DeleteCustomer;
    private com.k33ptoo.components.KButton JBtn_Refresh;
    private javax.swing.JLabel JBtn_SearchCustomer;
    private com.k33ptoo.components.KButton JBtn_UpdateCustomer;
    private javax.swing.JTable JTB_Customer;
    private GUI.JTextFieldCustom JTF_DiaChiKh;
    private GUI.JTextFieldCustom JTF_EmailKH;
    private GUI.JTextFieldCustom JTF_MaKH;
    private GUI.JTextFieldCustom JTF_SDTKH;
    private GUI.JTextFieldCustom JTF_SearchCustomer;
    private GUI.JTextFieldCustom JTF_TenKH;
    private javax.swing.JLabel JTxt_Header1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
