/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import BUS.CTNHAPKHO_BUS;
import BUS.DonVi_BUS;
import BUS.SanPham_BUS;
import DTO.CT_NhapKho_DTO;
import DTO.DonVi_DTO;
import DTO.SanPham_DTO;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.util.List;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author datsu
 */
public class JF_DetailOrder extends javax.swing.JFrame {

    /**
     * Creates new form JF_Customer
     */
    
    DefaultTableModel defaultTableModel;
    CTNHAPKHO_BUS ctNhapKho_BUS;
    SanPham_BUS product_BUS;
    DonVi_BUS dvt_BUS;
    List<SanPham_DTO> list_Product;
    List<CT_NhapKho_DTO> list_CTPNK;
    List<DonVi_DTO> list_DVT;
    
    
    
    public JF_DetailOrder(int maPNK) {
        
        initComponents();
        JTB_CTPNK.getTableHeader().setFont(new Font("Segoe UI", Font.PLAIN, 15));
        JTB_CTPNK.getTableHeader().setForeground(Color.black);
        JTB_CTPNK.getTableHeader().setPreferredSize(new Dimension(1234, 40));
        JTB_CTPNK.getColumnModel().getColumn(0).setPreferredWidth(100);
        JTB_CTPNK.getColumnModel().getColumn(0).setMaxWidth(100);
        
        
        ctNhapKho_BUS = new CTNHAPKHO_BUS();
        product_BUS = new SanPham_BUS();
        dvt_BUS = new DonVi_BUS();
        defaultTableModel = (DefaultTableModel) JTB_CTPNK.getModel();
        LoadDataTableCTNhapKho(maPNK);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        JTxt_Header1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTB_CTPNK = new javax.swing.JTable();
        JBtn_BackHome = new com.k33ptoo.components.KButton();
        JLB_MPNK = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel4.setBackground(new java.awt.Color(255, 153, 0));
        jPanel4.setPreferredSize(new java.awt.Dimension(1329, 93));

        JTxt_Header1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        JTxt_Header1.setForeground(new java.awt.Color(255, 255, 255));
        JTxt_Header1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JTxt_Header1.setText("CHI TIẾT PHIẾU NHẬP KHO");
        JTxt_Header1.setPreferredSize(new java.awt.Dimension(1236, 93));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JTxt_Header1, javax.swing.GroupLayout.DEFAULT_SIZE, 1027, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(JTxt_Header1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(245, 245, 245));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        JTB_CTPNK.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        JTB_CTPNK.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã SP", "Tên sản phẩm", "Số lượng", "ĐVT", "Thành tiền"
            }
        ));
        JTB_CTPNK.setGridColor(new java.awt.Color(204, 204, 204));
        JTB_CTPNK.setRowHeight(40);
        JTB_CTPNK.setSelectionBackground(new java.awt.Color(153, 153, 153));
        JTB_CTPNK.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        JTB_CTPNK.setShowGrid(false);
        jScrollPane1.setViewportView(JTB_CTPNK);

        JBtn_BackHome.setText("Quay lại");
        JBtn_BackHome.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        JBtn_BackHome.setkBackGroundColor(new java.awt.Color(255, 102, 0));
        JBtn_BackHome.setkBorderRadius(30);
        JBtn_BackHome.setkEndColor(new java.awt.Color(51, 153, 255));
        JBtn_BackHome.setkHoverEndColor(new java.awt.Color(51, 102, 255));
        JBtn_BackHome.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        JBtn_BackHome.setkHoverStartColor(new java.awt.Color(51, 102, 255));
        JBtn_BackHome.setkSelectedColor(new java.awt.Color(255, 102, 0));
        JBtn_BackHome.setkStartColor(new java.awt.Color(51, 153, 255));
        JBtn_BackHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtn_BackHomeActionPerformed(evt);
            }
        });

        JLB_MPNK.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        JLB_MPNK.setText("Mã phiếu nhập kho:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(JLB_MPNK)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JBtn_BackHome, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBtn_BackHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLB_MPNK))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 1027, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, "card2");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JBtn_BackHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtn_BackHomeActionPerformed
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_JBtn_BackHomeActionPerformed
    
    private void LoadDataTableCTNhapKho(int maPNK){
        defaultTableModel.setRowCount(0);
        JLB_MPNK.setText("Mã phiếu nhập kho: MPNK" + String.valueOf(maPNK));
        list_CTPNK = ctNhapKho_BUS.getCTNhapKho(maPNK);
        String maSP;
        String tenSP;
        String tenDVT;
        String thanhTienFormat;
        for(CT_NhapKho_DTO ctnk : list_CTPNK){
            if(ctnk.getMaSP() != null){
                maSP = ctnk.getMaSP();
                tenSP = getProductByMaSP(ctnk.getMaSP()).getTenSP();
            }
            else{
                maSP = "Null";
                tenSP = "Null";
            }
            tenDVT = getDVTByMaDVT(ctnk.getMaDVT()).getTenDV();
            thanhTienFormat = String.format("%.0f", ctnk.getThanhTien());
            defaultTableModel.addRow(new Object[] {maSP, tenSP, ctnk.getSoLuong(), tenDVT, thanhTienFormat});
        }
    }
    
    private SanPham_DTO getProductByMaSP(String maSP){
        list_Product = product_BUS.getAllProduct();
        for(SanPham_DTO sp : list_Product){
            if(sp.getMaSP().compareTo(maSP) == 0){
                return sp;
            }
        }
        return null;
    }
    
    private DonVi_DTO getDVTByMaDVT(String maDVT){
        list_DVT = dvt_BUS.getAllDVTChinh();
        for(DonVi_DTO dvt : list_DVT){
            if(dvt.getMaDV().compareTo(maDVT) == 0){
                return dvt;
            }
        }
        return null;
    }
    
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(JF_DetailOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(JF_DetailOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(JF_DetailOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(JF_DetailOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                int masp = 0;
//                new JF_DetailOrder(masp).setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KButton JBtn_BackHome;
    private javax.swing.JLabel JLB_MPNK;
    private javax.swing.JTable JTB_CTPNK;
    private javax.swing.JLabel JTxt_Header1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
