/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.awt.Color;
import javax.swing.JOptionPane;
/**
 *
 * @author daitr
 */
public class JF_Home extends javax.swing.JFrame {

    /**
     * Creates new form JF_Home
     */
    public JF_Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        JP_Dashbroad = new GUI.JPanelCustom();
        JP_Header = new GUI.JPanelCustom();
        JTxt_Header = new javax.swing.JLabel();
        jP_Panel2 = new GUI.JPanelCustom();
        JBtn_Bill = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        JBtn_Product = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        JBtn_Order = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        JBtn_Staff = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        JBtn_Customer = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        JBtn_Supplier = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        JBtn_Inventory = new javax.swing.JButton();
        JBtn_Sell = new javax.swing.JButton();
        JBtn_Logout = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JP_Dashbroad.setBackground(new java.awt.Color(255, 255, 255));

        JP_Header.setBackground(new java.awt.Color(255, 255, 255));

        JTxt_Header.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        JTxt_Header.setForeground(new java.awt.Color(255, 102, 0));
        JTxt_Header.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JTxt_Header.setText("HỆ THỐNG QUẢN LÝ NƯỚC GIẢI KHÁT");
        JTxt_Header.setPreferredSize(new java.awt.Dimension(1329, 93));

        javax.swing.GroupLayout JP_HeaderLayout = new javax.swing.GroupLayout(JP_Header);
        JP_Header.setLayout(JP_HeaderLayout);
        JP_HeaderLayout.setHorizontalGroup(
            JP_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JTxt_Header, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        JP_HeaderLayout.setVerticalGroup(
            JP_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_HeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JTxt_Header, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jP_Panel2.setBackground(new java.awt.Color(245, 245, 245));

        JBtn_Bill.setBackground(new java.awt.Color(255, 255, 255));
        JBtn_Bill.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon_bill.png"))); // NOI18N
        JBtn_Bill.setContentAreaFilled(false);
        JBtn_Bill.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JBtn_Bill.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        JBtn_Bill.setOpaque(true);
        JBtn_Bill.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JBtn_BillMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JBtn_BillMouseExited(evt);
            }
        });
        JBtn_Bill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtn_BillActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(192, 37));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ĐƠN HÀNG");
        jLabel1.setPreferredSize(new java.awt.Dimension(192, 37));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        JBtn_Product.setBackground(new java.awt.Color(255, 255, 255));
        JBtn_Product.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon_product.png"))); // NOI18N
        JBtn_Product.setContentAreaFilled(false);
        JBtn_Product.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JBtn_Product.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        JBtn_Product.setOpaque(true);
        JBtn_Product.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JBtn_ProductMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JBtn_ProductMouseExited(evt);
            }
        });
        JBtn_Product.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtn_ProductActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 153, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(192, 37));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("SẢN PHẨM");
        jLabel4.setPreferredSize(new java.awt.Dimension(192, 37));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        JBtn_Order.setBackground(new java.awt.Color(255, 255, 255));
        JBtn_Order.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon_order.png"))); // NOI18N
        JBtn_Order.setContentAreaFilled(false);
        JBtn_Order.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JBtn_Order.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        JBtn_Order.setOpaque(true);
        JBtn_Order.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JBtn_OrderMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JBtn_OrderMouseExited(evt);
            }
        });
        JBtn_Order.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtn_OrderActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 153, 0));
        jPanel3.setPreferredSize(new java.awt.Dimension(192, 37));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("NHẬP KHO");
        jLabel5.setPreferredSize(new java.awt.Dimension(192, 37));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 153, 0));
        jPanel4.setPreferredSize(new java.awt.Dimension(192, 37));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("BÁN HÀNG");
        jLabel6.setPreferredSize(new java.awt.Dimension(192, 37));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        JBtn_Staff.setBackground(new java.awt.Color(255, 255, 255));
        JBtn_Staff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon_staff.png"))); // NOI18N
        JBtn_Staff.setContentAreaFilled(false);
        JBtn_Staff.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JBtn_Staff.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        JBtn_Staff.setOpaque(true);
        JBtn_Staff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JBtn_StaffMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JBtn_StaffMouseExited(evt);
            }
        });
        JBtn_Staff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtn_StaffActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(255, 153, 0));
        jPanel5.setPreferredSize(new java.awt.Dimension(192, 37));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("NHÂN VIÊN");
        jLabel7.setPreferredSize(new java.awt.Dimension(192, 37));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        JBtn_Customer.setBackground(new java.awt.Color(255, 255, 255));
        JBtn_Customer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon_customer.png"))); // NOI18N
        JBtn_Customer.setContentAreaFilled(false);
        JBtn_Customer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JBtn_Customer.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        JBtn_Customer.setOpaque(true);
        JBtn_Customer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JBtn_CustomerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JBtn_CustomerMouseExited(evt);
            }
        });
        JBtn_Customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtn_CustomerActionPerformed(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(255, 153, 0));
        jPanel6.setPreferredSize(new java.awt.Dimension(192, 37));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("KHÁCH HÀNG");
        jLabel8.setPreferredSize(new java.awt.Dimension(192, 37));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        JBtn_Supplier.setBackground(new java.awt.Color(255, 255, 255));
        JBtn_Supplier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon_supplier.png"))); // NOI18N
        JBtn_Supplier.setContentAreaFilled(false);
        JBtn_Supplier.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JBtn_Supplier.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        JBtn_Supplier.setOpaque(true);
        JBtn_Supplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JBtn_SupplierMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JBtn_SupplierMouseExited(evt);
            }
        });
        JBtn_Supplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtn_SupplierActionPerformed(evt);
            }
        });

        jPanel7.setBackground(new java.awt.Color(255, 153, 0));
        jPanel7.setPreferredSize(new java.awt.Dimension(192, 37));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("NHÀ CUNG CẤP");
        jLabel9.setPreferredSize(new java.awt.Dimension(192, 37));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel8.setBackground(new java.awt.Color(255, 153, 0));
        jPanel8.setPreferredSize(new java.awt.Dimension(192, 37));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("TỒN KHO");
        jLabel10.setPreferredSize(new java.awt.Dimension(192, 37));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        JBtn_Inventory.setBackground(new java.awt.Color(255, 255, 255));
        JBtn_Inventory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon_warehouse.png"))); // NOI18N
        JBtn_Inventory.setContentAreaFilled(false);
        JBtn_Inventory.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JBtn_Inventory.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        JBtn_Inventory.setOpaque(true);
        JBtn_Inventory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JBtn_InventoryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JBtn_InventoryMouseExited(evt);
            }
        });
        JBtn_Inventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtn_InventoryActionPerformed(evt);
            }
        });

        JBtn_Sell.setBackground(new java.awt.Color(255, 255, 255));
        JBtn_Sell.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon_sell.png"))); // NOI18N
        JBtn_Sell.setContentAreaFilled(false);
        JBtn_Sell.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JBtn_Sell.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        JBtn_Sell.setOpaque(true);
        JBtn_Sell.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JBtn_SellMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JBtn_SellMouseExited(evt);
            }
        });
        JBtn_Sell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtn_SellActionPerformed(evt);
            }
        });

        JBtn_Logout.setBackground(new java.awt.Color(245, 245, 245));
        JBtn_Logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon_logout.png"))); // NOI18N
        JBtn_Logout.setContentAreaFilled(false);
        JBtn_Logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JBtn_Logout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        JBtn_Logout.setOpaque(true);
        JBtn_Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JBtn_LogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JBtn_LogoutMouseExited(evt);
            }
        });
        JBtn_Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtn_LogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jP_Panel2Layout = new javax.swing.GroupLayout(jP_Panel2);
        jP_Panel2.setLayout(jP_Panel2Layout);
        jP_Panel2Layout.setHorizontalGroup(
            jP_Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_Panel2Layout.createSequentialGroup()
                .addContainerGap(187, Short.MAX_VALUE)
                .addGroup(jP_Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jP_Panel2Layout.createSequentialGroup()
                        .addGroup(jP_Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JBtn_Inventory, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jP_Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JBtn_Staff, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jP_Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JBtn_Customer, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jP_Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JBtn_Supplier, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jP_Panel2Layout.createSequentialGroup()
                        .addGroup(jP_Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JBtn_Sell, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jP_Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JBtn_Bill, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jP_Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JBtn_Product, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jP_Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JBtn_Order, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(188, Short.MAX_VALUE))
            .addGroup(jP_Panel2Layout.createSequentialGroup()
                .addComponent(JBtn_Logout, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jP_Panel2Layout.setVerticalGroup(
            jP_Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_Panel2Layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addGroup(jP_Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jP_Panel2Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JBtn_Sell, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jP_Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jP_Panel2Layout.createSequentialGroup()
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(JBtn_Order, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jP_Panel2Layout.createSequentialGroup()
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(JBtn_Product, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jP_Panel2Layout.createSequentialGroup()
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(JBtn_Bill, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(27, 27, 27)
                .addGroup(jP_Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jP_Panel2Layout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JBtn_Inventory, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jP_Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jP_Panel2Layout.createSequentialGroup()
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(JBtn_Supplier, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jP_Panel2Layout.createSequentialGroup()
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(JBtn_Customer, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jP_Panel2Layout.createSequentialGroup()
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(JBtn_Staff, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(22, 22, 22)
                .addComponent(JBtn_Logout)
                .addContainerGap())
        );

        javax.swing.GroupLayout JP_DashbroadLayout = new javax.swing.GroupLayout(JP_Dashbroad);
        JP_Dashbroad.setLayout(JP_DashbroadLayout);
        JP_DashbroadLayout.setHorizontalGroup(
            JP_DashbroadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jP_Panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(JP_Header, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        JP_DashbroadLayout.setVerticalGroup(
            JP_DashbroadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_DashbroadLayout.createSequentialGroup()
                .addComponent(JP_Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jP_Panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JP_Dashbroad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JP_Dashbroad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JBtn_BillMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBtn_BillMouseExited
        JBtn_Bill.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_JBtn_BillMouseExited

    private void JBtn_BillMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBtn_BillMouseEntered
        JBtn_Bill.setBackground(new Color(255,153,0));
    }//GEN-LAST:event_JBtn_BillMouseEntered

    private void JBtn_ProductMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBtn_ProductMouseEntered
        JBtn_Product.setBackground(new Color(255,153,0));
    }//GEN-LAST:event_JBtn_ProductMouseEntered

    private void JBtn_ProductMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBtn_ProductMouseExited
        JBtn_Product.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_JBtn_ProductMouseExited

    private void JBtn_OrderMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBtn_OrderMouseEntered
        JBtn_Order.setBackground(new Color(255,153,0));
    }//GEN-LAST:event_JBtn_OrderMouseEntered

    private void JBtn_OrderMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBtn_OrderMouseExited
        JBtn_Order.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_JBtn_OrderMouseExited

    private void JBtn_StaffMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBtn_StaffMouseEntered
        // TODO add your handling code here:
        JBtn_Staff.setBackground(new Color(255,153,0));
    }//GEN-LAST:event_JBtn_StaffMouseEntered

    private void JBtn_StaffMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBtn_StaffMouseExited
        // TODO add your handling code here:
        JBtn_Staff.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_JBtn_StaffMouseExited

    private void JBtn_CustomerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBtn_CustomerMouseEntered
        // TODO add your handling code here:
        JBtn_Customer.setBackground(new Color(255,153,0));
    }//GEN-LAST:event_JBtn_CustomerMouseEntered

    private void JBtn_CustomerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBtn_CustomerMouseExited
        // TODO add your handling code here:
        JBtn_Customer.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_JBtn_CustomerMouseExited

    private void JBtn_SupplierMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBtn_SupplierMouseEntered
        JBtn_Supplier.setBackground(new Color(255,153,0));
    }//GEN-LAST:event_JBtn_SupplierMouseEntered

    private void JBtn_SupplierMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBtn_SupplierMouseExited
        JBtn_Supplier.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_JBtn_SupplierMouseExited

    private void JBtn_InventoryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBtn_InventoryMouseEntered
        JBtn_Inventory.setBackground(new Color(255,153,0));
    }//GEN-LAST:event_JBtn_InventoryMouseEntered

    private void JBtn_InventoryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBtn_InventoryMouseExited
        JBtn_Inventory.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_JBtn_InventoryMouseExited

    private void JBtn_SellMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBtn_SellMouseEntered
        JBtn_Sell.setBackground(new Color(255,153,0));
    }//GEN-LAST:event_JBtn_SellMouseEntered

    private void JBtn_SellMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBtn_SellMouseExited
        JBtn_Sell.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_JBtn_SellMouseExited

    private void JBtn_CustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtn_CustomerActionPerformed
       JF_Customer jF_Customer = new JF_Customer();
       jF_Customer.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_JBtn_CustomerActionPerformed

    private void JBtn_StaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtn_StaffActionPerformed
       JF_Staff JF_Staff = new JF_Staff();
       JF_Staff.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_JBtn_StaffActionPerformed

    private void JBtn_SupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtn_SupplierActionPerformed
       JF_Supplier JF_Supplier = new JF_Supplier();
       JF_Supplier.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_JBtn_SupplierActionPerformed

    private void JBtn_ProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtn_ProductActionPerformed
       JF_Product JF_Product = new JF_Product();
       JF_Product.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_JBtn_ProductActionPerformed

    private void JBtn_InventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtn_InventoryActionPerformed
       JF_WareHouse JF_WareHouse = new JF_WareHouse();
       JF_WareHouse.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_JBtn_InventoryActionPerformed

    private void JBtn_OrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtn_OrderActionPerformed
       JF_Order JF_Order = new JF_Order();
       JF_Order.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_JBtn_OrderActionPerformed

    private void JBtn_BillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtn_BillActionPerformed
       JF_Bill JF_Bill = new JF_Bill();
       JF_Bill.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_JBtn_BillActionPerformed

    private void JBtn_SellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtn_SellActionPerformed
       JF_Sell JF_Sell = new JF_Sell();
       JF_Sell.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_JBtn_SellActionPerformed

    private void JBtn_LogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBtn_LogoutMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_JBtn_LogoutMouseEntered

    private void JBtn_LogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBtn_LogoutMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_JBtn_LogoutMouseExited

    private void JBtn_LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtn_LogoutActionPerformed

        int confirm = JOptionPane.showConfirmDialog(this, "Bạn có muốn đăng xuất không?");
        if(confirm == JOptionPane.YES_OPTION){
             new JF_Login().setVisible(true);
             this.dispose();
        }
    }//GEN-LAST:event_JBtn_LogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBtn_Bill;
    private javax.swing.JButton JBtn_Customer;
    private javax.swing.JButton JBtn_Inventory;
    private javax.swing.JButton JBtn_Logout;
    private javax.swing.JButton JBtn_Order;
    private javax.swing.JButton JBtn_Product;
    private javax.swing.JButton JBtn_Sell;
    private javax.swing.JButton JBtn_Staff;
    private javax.swing.JButton JBtn_Supplier;
    private GUI.JPanelCustom JP_Dashbroad;
    private GUI.JPanelCustom JP_Header;
    private javax.swing.JLabel JTxt_Header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private GUI.JPanelCustom jP_Panel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    // End of variables declaration//GEN-END:variables
}
