/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import BUS.NhanVien_BUS;
import DTO.NhanVien_DTO;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author
 */
public class JF_Staff extends javax.swing.JFrame {

    /**
     * Creates new form JF_Customer
     * 
     */
    
    
    DefaultTableModel defaultTableModel;
    NhanVien_BUS staff_BUS;
    
    public JF_Staff() {
        initComponents();

        //giao dien
        JTable_Staff.getTableHeader().setFont(new Font("Segoe UI", Font.PLAIN, 15));
        JTable_Staff.getTableHeader().setForeground(Color.black);
        JTable_Staff.getTableHeader().setPreferredSize(new Dimension(1234, 40));
        JTable_Staff.getColumnModel().getColumn(0).setPreferredWidth(100);
        JTable_Staff.getColumnModel().getColumn(0).setMaxWidth(100);
        //
        
        
        defaultTableModel = (DefaultTableModel) JTable_Staff.getModel();
        staff_BUS = new NhanVien_BUS();
        
        LoadTableData();
        EventSelectRow();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        JTxt_Header1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        JTF_TenNV = new GUI.JTextFieldCustom();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JTF_SDTNV = new GUI.JTextFieldCustom();
        jLabel3 = new javax.swing.JLabel();
        JTF_DiaChiNV = new GUI.JTextFieldCustom();
        jLabel4 = new javax.swing.JLabel();
        JTF_EmailNV = new GUI.JTextFieldCustom();
        jLabel5 = new javax.swing.JLabel();
        JTF_MaNV = new GUI.JTextFieldCustom();
        JTF_SearchStaff = new GUI.JTextFieldCustom();
        jPanel7 = new javax.swing.JPanel();
        JBtn_AddStaff = new com.k33ptoo.components.KButton();
        JBtn_UpdateStaff = new com.k33ptoo.components.KButton();
        JBtn_BackHome = new com.k33ptoo.components.KButton();
        JBtn_DeleteStaff = new com.k33ptoo.components.KButton();
        JBtn_Refresh = new com.k33ptoo.components.KButton();
        JBtn_SearchStaff = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTable_Staff = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel4.setBackground(new java.awt.Color(255, 153, 0));
        jPanel4.setPreferredSize(new java.awt.Dimension(1329, 93));

        JTxt_Header1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        JTxt_Header1.setForeground(new java.awt.Color(255, 255, 255));
        JTxt_Header1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JTxt_Header1.setText("QUẢN LÝ NHÂN VIÊN");
        JTxt_Header1.setPreferredSize(new java.awt.Dimension(1236, 93));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JTxt_Header1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(JTxt_Header1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(245, 245, 245));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel1.setText("Tên nhân viên: ");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel2.setText("Số điện thoại:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel3.setText("Địa chỉ:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel4.setText("Email:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel5.setText("Mã NV:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(27, 27, 27)
                        .addComponent(JTF_MaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(31, 31, 31)
                        .addComponent(JTF_DiaChiNV, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JTF_TenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JTF_SDTNV, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(26, 26, 26)
                        .addComponent(JTF_EmailNV, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(51, 51, 51))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTF_MaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(36, 36, 36)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTF_TenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(JTF_SDTNV, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(39, 39, 39)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTF_DiaChiNV, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(JTF_EmailNV, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(50, 50, 50))
        );

        jPanel7.setBackground(new java.awt.Color(245, 245, 245));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JBtn_AddStaff.setText("Thêm");
        JBtn_AddStaff.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        JBtn_AddStaff.setkBackGroundColor(new java.awt.Color(255, 102, 0));
        JBtn_AddStaff.setkBorderRadius(30);
        JBtn_AddStaff.setkEndColor(new java.awt.Color(255, 153, 0));
        JBtn_AddStaff.setkHoverEndColor(new java.awt.Color(255, 153, 0));
        JBtn_AddStaff.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        JBtn_AddStaff.setkHoverStartColor(new java.awt.Color(255, 102, 0));
        JBtn_AddStaff.setkSelectedColor(new java.awt.Color(255, 102, 0));
        JBtn_AddStaff.setkStartColor(new java.awt.Color(255, 153, 0));
        JBtn_AddStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtn_AddStaffActionPerformed(evt);
            }
        });
        jPanel7.add(JBtn_AddStaff, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 160, -1));

        JBtn_UpdateStaff.setText("Cập nhật");
        JBtn_UpdateStaff.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        JBtn_UpdateStaff.setkBackGroundColor(new java.awt.Color(255, 102, 0));
        JBtn_UpdateStaff.setkBorderRadius(30);
        JBtn_UpdateStaff.setkEndColor(new java.awt.Color(255, 153, 0));
        JBtn_UpdateStaff.setkHoverEndColor(new java.awt.Color(255, 153, 0));
        JBtn_UpdateStaff.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        JBtn_UpdateStaff.setkHoverStartColor(new java.awt.Color(255, 102, 0));
        JBtn_UpdateStaff.setkSelectedColor(new java.awt.Color(255, 102, 0));
        JBtn_UpdateStaff.setkStartColor(new java.awt.Color(255, 153, 0));
        JBtn_UpdateStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtn_UpdateStaffActionPerformed(evt);
            }
        });
        jPanel7.add(JBtn_UpdateStaff, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 160, -1));

        JBtn_BackHome.setText("Về trang chủ");
        JBtn_BackHome.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        JBtn_BackHome.setkBackGroundColor(new java.awt.Color(255, 102, 0));
        JBtn_BackHome.setkBorderRadius(30);
        JBtn_BackHome.setkEndColor(new java.awt.Color(51, 153, 255));
        JBtn_BackHome.setkHoverEndColor(new java.awt.Color(51, 102, 255));
        JBtn_BackHome.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        JBtn_BackHome.setkHoverStartColor(new java.awt.Color(51, 102, 255));
        JBtn_BackHome.setkSelectedColor(new java.awt.Color(255, 102, 0));
        JBtn_BackHome.setkStartColor(new java.awt.Color(51, 153, 255));
        JBtn_BackHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtn_BackHomeActionPerformed(evt);
            }
        });
        jPanel7.add(JBtn_BackHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 160, -1));

        JBtn_DeleteStaff.setText("Xóa");
        JBtn_DeleteStaff.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        JBtn_DeleteStaff.setkBackGroundColor(new java.awt.Color(255, 102, 0));
        JBtn_DeleteStaff.setkBorderRadius(30);
        JBtn_DeleteStaff.setkEndColor(new java.awt.Color(255, 153, 0));
        JBtn_DeleteStaff.setkHoverEndColor(new java.awt.Color(255, 153, 0));
        JBtn_DeleteStaff.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        JBtn_DeleteStaff.setkHoverStartColor(new java.awt.Color(255, 102, 0));
        JBtn_DeleteStaff.setkSelectedColor(new java.awt.Color(255, 102, 0));
        JBtn_DeleteStaff.setkStartColor(new java.awt.Color(255, 153, 0));
        JBtn_DeleteStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtn_DeleteStaffActionPerformed(evt);
            }
        });
        jPanel7.add(JBtn_DeleteStaff, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 160, -1));

        JBtn_Refresh.setText("Làm mới");
        JBtn_Refresh.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        JBtn_Refresh.setkBackGroundColor(new java.awt.Color(255, 102, 0));
        JBtn_Refresh.setkBorderRadius(30);
        JBtn_Refresh.setkEndColor(new java.awt.Color(255, 153, 0));
        JBtn_Refresh.setkHoverEndColor(new java.awt.Color(255, 153, 0));
        JBtn_Refresh.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        JBtn_Refresh.setkHoverStartColor(new java.awt.Color(255, 102, 0));
        JBtn_Refresh.setkSelectedColor(new java.awt.Color(255, 102, 0));
        JBtn_Refresh.setkStartColor(new java.awt.Color(255, 153, 0));
        JBtn_Refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtn_RefreshActionPerformed(evt);
            }
        });
        jPanel7.add(JBtn_Refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 160, -1));

        JBtn_SearchStaff.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JBtn_SearchStaff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon_search.png"))); // NOI18N
        JBtn_SearchStaff.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JBtn_SearchStaff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JBtn_SearchStaffMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(JTF_SearchStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 1159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JBtn_SearchStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 3, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JTF_SearchStaff, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JBtn_SearchStaff, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new java.awt.CardLayout());

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        JTable_Staff.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        JTable_Staff.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MNV", "Tên nhân viên", "Số điện thoại", "Địa chỉ", "Email"
            }
        ));
        JTable_Staff.setGridColor(new java.awt.Color(204, 204, 204));
        JTable_Staff.setRowHeight(40);
        JTable_Staff.setSelectionBackground(new java.awt.Color(153, 153, 153));
        JTable_Staff.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        JTable_Staff.setShowGrid(false);
        jScrollPane1.setViewportView(JTable_Staff);

        jPanel6.add(jScrollPane1, "card2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 1234, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, "card2");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    private void LoadTableData(){ 
        
        defaultTableModel.setRowCount(0);
        List<NhanVien_DTO> listNV = staff_BUS.getAllStaff();
        for(NhanVien_DTO nv : listNV){
            defaultTableModel.addRow(new Object[] {nv.getMaNV(), nv.getTenNV(), nv.getSdtNV(), nv.getDiaChiNV(), nv.getEmailNV()});
        }
    }
    
    private void EventSelectRow(){
        ListSelectionModel listSelectionModel = JTable_Staff.getSelectionModel();
        listSelectionModel.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                int row = JTable_Staff.getSelectedRow();
                
                if(row >= 0){
                    String maNV = String.valueOf(JTable_Staff.getValueAt(row, 0));
                    String tenNV = String.valueOf(JTable_Staff.getValueAt(row, 1));
                    String sdtNV = String.valueOf(JTable_Staff.getValueAt(row, 2));
                    String diaChiNV = String.valueOf(JTable_Staff.getValueAt(row, 3));
                    String emailNV = String.valueOf(JTable_Staff.getValueAt(row, 4));

                    JTF_MaNV.setText(maNV);
                    JTF_TenNV.setText(tenNV);
                    JTF_SDTNV.setText(sdtNV);
                    JTF_DiaChiNV.setText(diaChiNV);
                    JTF_EmailNV.setText(emailNV);

                    JTF_MaNV.setEnabled(false);
                    JBtn_AddStaff.setEnabled(false);
                    
                }
           }
        });
    }
    
    private void ClearTextFiled(){
        JTF_MaNV.setText("");
        JTF_TenNV.setText("");
        JTF_SDTNV.setText("");
        JTF_DiaChiNV.setText("");
        JTF_EmailNV.setText("");
    }
    
    
    private void JBtn_BackHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtn_BackHomeActionPerformed
        JF_Home jF_Home = new JF_Home();
        jF_Home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_JBtn_BackHomeActionPerformed

    private NhanVien_DTO getDataStaffFromGUI(){
        
        String maNV = JTF_MaNV.getText();
        String tenNV = JTF_TenNV.getText();
        String sdtNV = JTF_SDTNV.getText();
        String diaChiNV = JTF_DiaChiNV.getText();
        String emailNV = JTF_EmailNV.getText();
        
        NhanVien_DTO nv = new NhanVien_DTO();
        nv.setMaNV(maNV);
        nv.setTenNV(tenNV);
        nv.setSdtNV(sdtNV);
        nv.setDiaChiNV(diaChiNV);
        nv.setEmailNV(emailNV);
        
        return nv;
    }
    
    private void JBtn_AddStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtn_AddStaffActionPerformed
        
        if(JTF_MaNV.getText().compareTo("") != 0 && JTF_TenNV.getText().compareTo("") != 0){
            staff_BUS.AddStaff(getDataStaffFromGUI());
            LoadTableData();
            JOptionPane.showMessageDialog(this, "Thêm thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            ClearTextFiled();
        }
        else{
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập thông tin nhân viên", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_JBtn_AddStaffActionPerformed

    private void JBtn_RefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtn_RefreshActionPerformed
        ClearTextFiled();
        JTF_MaNV.setEnabled(true);
        JBtn_AddStaff.setEnabled(true);
    }//GEN-LAST:event_JBtn_RefreshActionPerformed

    private void JBtn_UpdateStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtn_UpdateStaffActionPerformed

            int row = JTable_Staff.getSelectedRow();
            
            if(row >= 0){
                defaultTableModel.setRowCount(0);
                staff_BUS.UpdateStaff(getDataStaffFromGUI());
                LoadTableData();
                JOptionPane.showMessageDialog(this, "Sửa thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                ClearTextFiled();
                JTF_MaNV.setEnabled(true);
                JBtn_AddStaff.setEnabled(false);
            }
            else{
                JOptionPane.showMessageDialog(this, "Bạn chưa chọn nhân viên cần sửa", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            }
    }//GEN-LAST:event_JBtn_UpdateStaffActionPerformed

    private void JBtn_DeleteStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtn_DeleteStaffActionPerformed
        int row = JTable_Staff.getSelectedRow();
        
        if(row >= 0){
            int confirm = JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa không?");
        
            if(confirm == JOptionPane.YES_OPTION){
                String maNV = JTF_MaNV.getText();
                staff_BUS.DeleteStaff(maNV);
                
                LoadTableData();
                JOptionPane.showMessageDialog(this, "Xóa thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                ClearTextFiled();  
            }
        }
        else{
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn nhân viên cần xóa", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_JBtn_DeleteStaffActionPerformed

    private void JBtn_SearchStaffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBtn_SearchStaffMouseClicked
        if(JTF_SearchStaff.getText().length() > 0){
            String tenNV = JTF_SearchStaff.getText();
 
            defaultTableModel.setRowCount(0);
            List<NhanVien_DTO> listNV = staff_BUS.SearchStaff(tenNV);
            for(NhanVien_DTO nv : listNV){
                defaultTableModel.addRow(new Object[] {nv.getMaNV(), nv.getTenNV(), nv.getSdtNV(), nv.getDiaChiNV(), nv.getEmailNV()});
            }
        }
        else{
            LoadTableData();
        }
    }//GEN-LAST:event_JBtn_SearchStaffMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_Staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_Staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_Staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_Staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_Staff().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KButton JBtn_AddStaff;
    private com.k33ptoo.components.KButton JBtn_BackHome;
    private com.k33ptoo.components.KButton JBtn_DeleteStaff;
    private com.k33ptoo.components.KButton JBtn_Refresh;
    private javax.swing.JLabel JBtn_SearchStaff;
    private com.k33ptoo.components.KButton JBtn_UpdateStaff;
    private GUI.JTextFieldCustom JTF_DiaChiNV;
    private GUI.JTextFieldCustom JTF_EmailNV;
    private GUI.JTextFieldCustom JTF_MaNV;
    private GUI.JTextFieldCustom JTF_SDTNV;
    private GUI.JTextFieldCustom JTF_SearchStaff;
    private GUI.JTextFieldCustom JTF_TenNV;
    private javax.swing.JTable JTable_Staff;
    private javax.swing.JLabel JTxt_Header1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
