/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import BUS.CTDonHang_BUS;
import BUS.DonHang_BUS;
import BUS.DonVi_BUS;
import BUS.KhachHang_BUS;
import BUS.NhanVien_BUS;
import BUS.SanPham_BUS;
import BUS.TonKho_BUS;
import DTO.CT_DonHang_DTO;
import DTO.DonHang_DTO;
import DTO.DonVi_DTO;
import DTO.KhachHang_DTO;
import DTO.NhanVien_DTO;
import DTO.SanPham_DTO;
import DTO.TonKho_DTO;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author datsu
 */
public class JF_Sell extends javax.swing.JFrame {

    /**
     * Creates new form JF_Sell
     */
    
    DefaultTableModel defaultTableModel_SP;
    DefaultTableModel defaultTableModel_HD;
    DonVi_DTO dv_DTO;
    KhachHang_DTO kh_DTO;
    TonKho_BUS tonKho_BUS;
    SanPham_BUS sanPham_BUS;
    DonVi_BUS dv_BUS;
    NhanVien_BUS nv_BUS;
    KhachHang_BUS kh_BUS;
    DonHang_BUS dh_BUS;
    CTDonHang_BUS ctDH_BUS;
    List<SanPham_DTO> list_SP;
    List<DonVi_DTO> list_DV;
    List<TonKho_DTO> list_TK;
    
    boolean LoadSuccessCB_DVT = true;
    
    
    SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
    SimpleDateFormat dateFormatSQL = new SimpleDateFormat("yyyy/MM/dd");
    
    //int htBan = 0; //0 ban si, 1 ban le
    
    
    public JF_Sell() {
        initComponents();
        
        JTB_SP.getTableHeader().setFont(new Font("Segoe UI", Font.PLAIN, 15));
        JTB_SP.getTableHeader().setForeground(Color.black);
        JTB_SP.getTableHeader().setPreferredSize(new Dimension(1234, 40));
        JTB_SP.getColumnModel().getColumn(0).setPreferredWidth(100);
        JTB_SP.getColumnModel().getColumn(0).setMaxWidth(100);
        
        JTB_HD.getTableHeader().setFont(new Font("Segoe UI", Font.PLAIN, 15));
        JTB_HD.getTableHeader().setForeground(Color.black);
        JTB_HD.getTableHeader().setPreferredSize(new Dimension(1234, 40));
        JTB_HD.getColumnModel().getColumn(0).setPreferredWidth(50);
        JTB_HD.getColumnModel().getColumn(0).setMaxWidth(50);
        JTB_HD.getColumnModel().getColumn(2).setPreferredWidth(100);
        JTB_HD.getColumnModel().getColumn(2).setMaxWidth(100);
        JTB_HD.getColumnModel().getColumn(3).setPreferredWidth(80);
        JTB_HD.getColumnModel().getColumn(3).setMaxWidth(80);
        JTB_HD.getColumnModel().getColumn(4).setPreferredWidth(80);
        JTB_HD.getColumnModel().getColumn(4).setMaxWidth(80);
        
        defaultTableModel_SP = (DefaultTableModel) JTB_SP.getModel();
        defaultTableModel_HD = (DefaultTableModel) JTB_HD.getModel();
        kh_DTO = new KhachHang_DTO();
        dv_DTO = new DonVi_DTO();
        tonKho_BUS = new TonKho_BUS();
        sanPham_BUS = new SanPham_BUS();
        dv_BUS = new DonVi_BUS();
        nv_BUS = new NhanVien_BUS();
        kh_BUS = new KhachHang_BUS();
        dh_BUS = new DonHang_BUS();
        ctDH_BUS = new CTDonHang_BUS();
        list_SP = sanPham_BUS.getAllProduct();
        list_DV = dv_BUS.getAllDVT();
        list_TK = tonKho_BUS.getAllTonKho();
        
        Date date = new Date();
        JDC_Date.setDate(date);
        LoadTableData(tonKho_BUS.getAllTonKho());
        LoadNV(nv_BUS.getAllStaff());
        LoadCBKH();
        EventSelectRow();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        JTxt_Header2 = new javax.swing.JLabel();
        JBtn_BackHome = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        JP_SanPham = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTB_SP = new javax.swing.JTable();
        JTF_SearchProduct = new GUI.JTextFieldCustom();
        JBTN_SearchProduct = new javax.swing.JLabel();
        JP_TTSanPham = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        JTF_TenSP = new GUI.JTextFieldCustom();
        jLabel4 = new javax.swing.JLabel();
        JTF_Gia = new GUI.JTextFieldCustom();
        jLabel5 = new javax.swing.JLabel();
        JTF_SL = new GUI.JTextFieldCustom();
        JCB_HTBan = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        JCB_DVT = new javax.swing.JComboBox<>();
        JBTN_Them = new com.k33ptoo.components.KButton();
        JF_HoaDon = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        JTB_HD = new javax.swing.JTable();
        JBTN_XoaSP = new com.k33ptoo.components.KButton();
        JBTN_XacNhan = new com.k33ptoo.components.KButton();
        JF_ThanhToan = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        JTF_MaHD = new GUI.JTextFieldCustom();
        jLabel10 = new javax.swing.JLabel();
        JTF_TongTien = new GUI.JTextFieldCustom();
        JCB_NV = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        JCB_KH = new javax.swing.JComboBox<>();
        JBTN_ThanhToan = new com.k33ptoo.components.KButton();
        JBTN_TaoHDMoi = new com.k33ptoo.components.KButton();
        JDC_Date = new com.toedter.calendar.JDateChooser();
        jLabel14 = new javax.swing.JLabel();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel5.setBackground(new java.awt.Color(255, 153, 0));
        jPanel5.setPreferredSize(new java.awt.Dimension(1329, 93));

        JTxt_Header2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        JTxt_Header2.setForeground(new java.awt.Color(255, 255, 255));
        JTxt_Header2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JTxt_Header2.setText("BÁN HÀNG");
        JTxt_Header2.setPreferredSize(new java.awt.Dimension(1236, 93));

        JBtn_BackHome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JBtn_BackHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon_home.png"))); // NOI18N
        JBtn_BackHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JBtn_BackHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JBtn_BackHomeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(301, 301, 301)
                .addComponent(JTxt_Header2, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JBtn_BackHome, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JBtn_BackHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(JTxt_Header2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 1, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        JP_SanPham.setBackground(new java.awt.Color(245, 245, 245));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel1.setText("DANH MỤC SẢN PHẨM");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setLayout(new java.awt.CardLayout());

        JTB_SP.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        JTB_SP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MSP", "Tên SP", "SLT", "SLT (Quy đổi)"
            }
        ));
        JTB_SP.setGridColor(new java.awt.Color(204, 204, 204));
        JTB_SP.setRowHeight(40);
        JTB_SP.setSelectionBackground(new java.awt.Color(153, 153, 153));
        jScrollPane1.setViewportView(JTB_SP);

        jPanel4.add(jScrollPane1, "card2");

        JBTN_SearchProduct.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JBTN_SearchProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon_search.png"))); // NOI18N
        JBTN_SearchProduct.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JBTN_SearchProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JBTN_SearchProductMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout JP_SanPhamLayout = new javax.swing.GroupLayout(JP_SanPham);
        JP_SanPham.setLayout(JP_SanPhamLayout);
        JP_SanPhamLayout.setHorizontalGroup(
            JP_SanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(JP_SanPhamLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JTF_SearchProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JBTN_SearchProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        JP_SanPhamLayout.setVerticalGroup(
            JP_SanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_SanPhamLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(JP_SanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JTF_SearchProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JBTN_SearchProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        JP_TTSanPham.setBackground(new java.awt.Color(245, 245, 245));

        jPanel7.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel2.setText("THÔNG TIN SẢN PHẨM");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel3.setText("Tên sản phẩm:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel4.setText("Giá tiền:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel5.setText("Số lượng:");

        JCB_HTBan.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        JCB_HTBan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bán sỉ", "Bán lẻ" }));
        JCB_HTBan.setBorder(null);
        JCB_HTBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCB_HTBanActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel13.setText("Hình thức bán:");

        JCB_DVT.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        JCB_DVT.setBorder(null);
        JCB_DVT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCB_DVTActionPerformed(evt);
            }
        });

        JBTN_Them.setText("Thêm vào hóa đơn");
        JBTN_Them.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        JBTN_Them.setkBackGroundColor(new java.awt.Color(255, 102, 0));
        JBTN_Them.setkBorderRadius(30);
        JBTN_Them.setkEndColor(new java.awt.Color(255, 153, 0));
        JBTN_Them.setkHoverEndColor(new java.awt.Color(255, 153, 0));
        JBTN_Them.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        JBTN_Them.setkHoverStartColor(new java.awt.Color(255, 102, 0));
        JBTN_Them.setkSelectedColor(new java.awt.Color(255, 102, 0));
        JBTN_Them.setkStartColor(new java.awt.Color(255, 153, 0));
        JBTN_Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTN_ThemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JP_TTSanPhamLayout = new javax.swing.GroupLayout(JP_TTSanPham);
        JP_TTSanPham.setLayout(JP_TTSanPhamLayout);
        JP_TTSanPhamLayout.setHorizontalGroup(
            JP_TTSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(JP_TTSanPhamLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(JP_TTSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JP_TTSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(JP_TTSanPhamLayout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(JTF_TenSP, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(JP_TTSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JP_TTSanPhamLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(JTF_Gia, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JP_TTSanPhamLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(JTF_SL, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JCB_DVT, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(JP_TTSanPhamLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JCB_HTBan, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JP_TTSanPhamLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JBTN_Them, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(191, 191, 191))
        );
        JP_TTSanPhamLayout.setVerticalGroup(
            JP_TTSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_TTSanPhamLayout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JP_TTSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(JCB_HTBan, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JP_TTSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTF_TenSP, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(JP_TTSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTF_Gia, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(13, 13, 13)
                .addGroup(JP_TTSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTF_SL, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(JCB_DVT, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(JBTN_Them, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        JF_HoaDon.setBackground(new java.awt.Color(245, 245, 245));

        jPanel8.setBackground(new java.awt.Color(204, 204, 204));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel6.setText("HÓA ĐƠN");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addContainerGap())
        );

        JTB_HD.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        JTB_HD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MSP", "Tên SP", "Đơn giá", "ĐVT", "SL", "Thành tiền"
            }
        ));
        JTB_HD.setGridColor(new java.awt.Color(204, 204, 204));
        JTB_HD.setRowHeight(40);
        JTB_HD.setSelectionBackground(new java.awt.Color(153, 153, 153));
        jScrollPane2.setViewportView(JTB_HD);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        JBTN_XoaSP.setText("Xóa sản phẩm");
        JBTN_XoaSP.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        JBTN_XoaSP.setkBackGroundColor(new java.awt.Color(255, 102, 0));
        JBTN_XoaSP.setkBorderRadius(30);
        JBTN_XoaSP.setkEndColor(new java.awt.Color(255, 153, 0));
        JBTN_XoaSP.setkHoverEndColor(new java.awt.Color(255, 153, 0));
        JBTN_XoaSP.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        JBTN_XoaSP.setkHoverStartColor(new java.awt.Color(255, 102, 0));
        JBTN_XoaSP.setkSelectedColor(new java.awt.Color(255, 102, 0));
        JBTN_XoaSP.setkStartColor(new java.awt.Color(255, 153, 0));
        JBTN_XoaSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTN_XoaSPActionPerformed(evt);
            }
        });

        JBTN_XacNhan.setText("Xác nhận");
        JBTN_XacNhan.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        JBTN_XacNhan.setkBackGroundColor(new java.awt.Color(255, 102, 0));
        JBTN_XacNhan.setkBorderRadius(30);
        JBTN_XacNhan.setkEndColor(new java.awt.Color(255, 153, 0));
        JBTN_XacNhan.setkHoverEndColor(new java.awt.Color(255, 153, 0));
        JBTN_XacNhan.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        JBTN_XacNhan.setkHoverStartColor(new java.awt.Color(255, 102, 0));
        JBTN_XacNhan.setkSelectedColor(new java.awt.Color(255, 102, 0));
        JBTN_XacNhan.setkStartColor(new java.awt.Color(255, 153, 0));
        JBTN_XacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTN_XacNhanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JF_HoaDonLayout = new javax.swing.GroupLayout(JF_HoaDon);
        JF_HoaDon.setLayout(JF_HoaDonLayout);
        JF_HoaDonLayout.setHorizontalGroup(
            JF_HoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(JF_HoaDonLayout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(JBTN_XoaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(JBTN_XacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JF_HoaDonLayout.setVerticalGroup(
            JF_HoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JF_HoaDonLayout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(JF_HoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBTN_XoaSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBTN_XacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        JF_ThanhToan.setBackground(new java.awt.Color(245, 245, 245));

        jPanel10.setBackground(new java.awt.Color(204, 204, 204));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel7.setText("THANH TOÁN");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel8.setText("Mã ĐH:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel10.setText("Tổng tiền:");

        JCB_NV.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        JCB_NV.setBorder(null);
        JCB_NV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCB_NVActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel11.setText("Nhân viên:");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel12.setText("Khách hàng:");

        JCB_KH.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        JCB_KH.setBorder(null);
        JCB_KH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCB_KHActionPerformed(evt);
            }
        });

        JBTN_ThanhToan.setText("Thanh toán");
        JBTN_ThanhToan.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        JBTN_ThanhToan.setkBackGroundColor(new java.awt.Color(255, 102, 0));
        JBTN_ThanhToan.setkBorderRadius(30);
        JBTN_ThanhToan.setkEndColor(new java.awt.Color(255, 153, 0));
        JBTN_ThanhToan.setkHoverEndColor(new java.awt.Color(255, 153, 0));
        JBTN_ThanhToan.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        JBTN_ThanhToan.setkHoverStartColor(new java.awt.Color(255, 102, 0));
        JBTN_ThanhToan.setkSelectedColor(new java.awt.Color(255, 102, 0));
        JBTN_ThanhToan.setkStartColor(new java.awt.Color(255, 153, 0));
        JBTN_ThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTN_ThanhToanActionPerformed(evt);
            }
        });

        JBTN_TaoHDMoi.setText("Tạo hóa đơn mới");
        JBTN_TaoHDMoi.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        JBTN_TaoHDMoi.setkBackGroundColor(new java.awt.Color(255, 102, 0));
        JBTN_TaoHDMoi.setkBorderRadius(30);
        JBTN_TaoHDMoi.setkEndColor(new java.awt.Color(255, 153, 0));
        JBTN_TaoHDMoi.setkHoverEndColor(new java.awt.Color(255, 153, 0));
        JBTN_TaoHDMoi.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        JBTN_TaoHDMoi.setkHoverStartColor(new java.awt.Color(255, 102, 0));
        JBTN_TaoHDMoi.setkSelectedColor(new java.awt.Color(255, 102, 0));
        JBTN_TaoHDMoi.setkStartColor(new java.awt.Color(255, 153, 0));
        JBTN_TaoHDMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTN_TaoHDMoiActionPerformed(evt);
            }
        });

        JDC_Date.setDateFormatString("dd/MM/yyyy");
        JDC_Date.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel14.setText("Ngày lập:");

        javax.swing.GroupLayout JF_ThanhToanLayout = new javax.swing.GroupLayout(JF_ThanhToan);
        JF_ThanhToan.setLayout(JF_ThanhToanLayout);
        JF_ThanhToanLayout.setHorizontalGroup(
            JF_ThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(JF_ThanhToanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JF_ThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JF_ThanhToanLayout.createSequentialGroup()
                        .addGroup(JF_ThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(JF_ThanhToanLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(JTF_MaHD, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(JF_ThanhToanLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JCB_NV, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(JF_ThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(JF_ThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JCB_KH, 0, 187, Short.MAX_VALUE)
                            .addComponent(JDC_Date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(JF_ThanhToanLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JTF_TongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JF_ThanhToanLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JBTN_ThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JBTN_TaoHDMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101))
        );
        JF_ThanhToanLayout.setVerticalGroup(
            JF_ThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JF_ThanhToanLayout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(JF_ThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(JF_ThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(JTF_MaHD, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)
                        .addComponent(jLabel14))
                    .addComponent(JDC_Date, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JF_ThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JCB_NV, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(JCB_KH, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(JF_ThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTF_TongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(JF_ThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBTN_ThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBTN_TaoHDMoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(JF_HoaDon, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JP_SanPham, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JP_TTSanPham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JF_ThanhToan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JP_SanPham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JP_TTSanPham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JF_HoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JF_ThanhToan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 1208, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, "card2");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    private void LoadTableData(List<TonKho_DTO> listSPTK){ 
        defaultTableModel_SP.setRowCount(0);
        for(TonKho_DTO spTK : listSPTK){
            String tenSP = getProductByMaSP(spTK.getMaSP()).getTenSP();
            defaultTableModel_SP.addRow(new Object[] {spTK.getMaSP(), tenSP, spTK.getSlTon(), spTK.getSlTonQuiDoi()});
        }
    }
    
    private void LoadNV(List<NhanVien_DTO> listNV){
        for(NhanVien_DTO nv : listNV){
            JCB_NV.addItem(nv);
        }
    }
    
    private void LoadCBKH(){
        JCB_KH.removeAllItems();
        if(JCB_HTBan.getSelectedIndex() == 0){
             //load CB Khachhang si
             List<KhachHang_DTO> listKHSi = kh_BUS.getAllKhachSi();
             for(KhachHang_DTO kh : listKHSi){
                JCB_KH.addItem(kh);
             }
         }
         else{
            JCB_KH.addItem(kh_BUS.KHLe()); 
         }
    }
    
    private void RefreshJFrame(){
        JBTN_Them.setEnabled(true);
        JBTN_XoaSP.setEnabled(true);
        JBTN_XacNhan.setEnabled(true);
        JBTN_TaoHDMoi.setEnabled(true);
        JCB_HTBan.setEnabled(true);
        JTF_TenSP.setText("");
        JTF_Gia.setText("");
        JTF_SL.setText("");
        defaultTableModel_HD.setRowCount(0);
        JTF_MaHD.setText("");
        JTF_TongTien.setText("");
        LoadTableData(tonKho_BUS.getAllTonKho());
    }
    
    private void EventSelectRow(){
        ListSelectionModel listSelectionModel = JTB_SP.getSelectionModel();
        listSelectionModel.setSelectionMode(ListSelectionModel.SINGLE_SELECTION); 
        listSelectionModel.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if(!e.getValueIsAdjusting()){
                    int row = JTB_SP.getSelectedRow();
                    if(row >= 0){
                        String maSP = String.valueOf(JTB_SP.getValueAt(row, 0));
                        String tenSP = String.valueOf(JTB_SP.getValueAt(row, 1));
                        SanPham_DTO spSelected = getProductByMaSP(maSP);
                        JTF_TenSP.setText(tenSP);
                        
                        //load DVT
                        LoadSuccessCB_DVT = false;
                        JCB_DVT.removeAllItems();
                        String dvtc = spSelected.getDvtChinh();
                        String dvtp = spSelected.getDvtPhu();
                        List<DonVi_DTO> listDVT = getListDVTByMaDVT_SP(dvtc, dvtp);
                        for(DonVi_DTO dvt : listDVT){
                            
                            JCB_DVT.addItem(dvt);
                        }
                        
                        LoadSuccessCB_DVT = true;
                        // si, le
                        DonVi_DTO dvt = (DonVi_DTO) JCB_DVT.getSelectedItem();
                        eventGiaBanSiLe(row, spSelected);
                    }
                }
            }
        });
    }
    
    private int kiemTraDongTonTaiSPTrongHD(String maSP, String tenDVT){
        int tongDong = JTB_HD.getRowCount();
        for(int i = 0; i < tongDong; i++){
            String idsp = (String) defaultTableModel_HD.getValueAt(i, 0);
            String dvt = (String) defaultTableModel_HD.getValueAt(i, 3);
            if(idsp.compareTo(maSP) == 0 && dvt.compareTo(tenDVT) == 0){
                return i;
            }
        }
        return -1;
    }
    
    private SanPham_DTO getProductByMaSP(String maSP){
        for(SanPham_DTO sp : list_SP){
            if(sp.getMaSP().compareTo(maSP) == 0){
                return sp;
            }
        }
        return null;
    }
    
    private TonKho_DTO getTonKhoByMaSP(String maSP){
        for(TonKho_DTO tk : list_TK){
            if(tk.getMaSP().compareTo(maSP) == 0){
                return tk;
            }
        }
        return null;
    }
    
    private DonVi_DTO getDonViByTenDV_SP(String tenDV_SP){
        for(DonVi_DTO dv : list_DV){
            if(dv.getTenDV().compareTo(tenDV_SP) == 0){
                return dv;
            }
        }
        return null;
    }
    
    private List<DonVi_DTO> getListDVTByMaDVT_SP(String dvtc, String dvtp){
        List<DonVi_DTO> listDVT = new ArrayList<>();
        for(DonVi_DTO dvt : list_DV){
            if(dvt.getTenDV().compareTo(dvtc) == 0 || dvt.getTenDV().compareTo(dvtp) == 0){
                listDVT.add(dvt);
            }
        }
        return listDVT;
    }
    
    private int layDongTBSP_CapNhatTK(String maSp){
        int tongDong = JTB_SP.getRowCount();
        String maSP_TBSP;
        for(int i = 0; i < tongDong; i++){
            maSP_TBSP = String.valueOf(JTB_SP.getValueAt(i, 0));
            if(maSP_TBSP.compareTo(maSp) == 0){
                return i;
            }
        }
        return -1;
    }
    
    private boolean checkDVTC_DVTP(String tenDVT){
        List<DonVi_DTO> listDVT = dv_BUS.getAllDVT();
        for(DonVi_DTO dv : listDVT){
            if(dv.getTenDV().compareTo(tenDVT) == 0 && dv.getDVTC() == 1){
                return true;//dvt chinh
            }
        }
        return false; //dvt phu
    }
    
    private String tinhTonKhoQuyDoi(String dvtc, String dvtp, int sltk, int sldvtp){
        int sl_dvtc = sltk/sldvtp;
        int sl_dvtp = 0;
        if(sltk%sldvtp != 0){
            sl_dvtp = sltk - sl_dvtc*sldvtp;
        }
        return sl_dvtc + " " + dvtc + " " + sl_dvtp + " " + dvtp;
    }
    
    private void addSPVaoTB_CTHD(int rowSelected, String maSP){
        JCB_HTBan.setEnabled(false);
        int slSP = Integer.parseInt(JTF_SL.getText());
        String tenDVT = String.valueOf(JCB_DVT.getSelectedItem());
        if(kiemTraDongTonTaiSPTrongHD(maSP, tenDVT) != -1){ //trung
            int soDongTonTai = kiemTraDongTonTaiSPTrongHD(maSP, tenDVT);
            int sl = (int) JTB_HD.getValueAt(soDongTonTai, 4);
            int capNhatSL = slSP + sl;
            float giaTien = Float.parseFloat(JTF_Gia.getText());
            String capNhatThanhTien = String.format("%.0f", giaTien * capNhatSL);

            JTB_HD.setValueAt(capNhatSL, soDongTonTai, 4);
            JTB_HD.setValueAt(capNhatThanhTien, soDongTonTai, 5);
        }
        else { //kh trung
            int sl = Integer.parseInt(JTF_SL.getText());
            float giaBan = Float.parseFloat(JTF_Gia.getText());
            String giaBanFormat = String.format("%.0f", giaBan);
            String thanhTien = String.format("%.0f", giaBan*sl);
            defaultTableModel_HD.addRow(new Object[] {maSP , JTF_TenSP.getText(), giaBanFormat, String.valueOf(JCB_DVT.getSelectedItem()), sl, thanhTien});
        }
    }
    
    private void eventGiaBanSiLe(int rowSelected, SanPham_DTO sp){
        if(LoadSuccessCB_DVT){
            DonVi_DTO dvt = (DonVi_DTO) JCB_DVT.getSelectedItem();
            
            String giaTien;
            rowSelected = JTB_SP.getSelectedRow();
            sp = getProductByMaSP(String.valueOf(JTB_SP.getValueAt(rowSelected, 0)));

            //ban si
            if(JCB_HTBan.getSelectedIndex() == 0){ //si
 
                if(dvt.getDVTC() == 1){ //dvt chinh
                    giaTien = String.format("%.0f", sp.getGiaBanSi_DVTC());
                    JTF_Gia.setText(giaTien);
                }
                else{
                    giaTien = String.format("%.0f", sp.getGiaBanSi_DVTP());
                    JTF_Gia.setText(giaTien);
                }            
            }
            else{
                
                if(dvt.getDVTC() == 1){ //dvt chinh
                    giaTien = String.format("%.0f", sp.getGiaBanLe_DVTC());
                    JTF_Gia.setText(giaTien);
                }
                else{
                    giaTien = String.format("%.0f", sp.getGiabanLe_DVTP());
                    JTF_Gia.setText(giaTien);
                }           
            }
        }
    }
    
    
    private void JCB_HTBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCB_HTBanActionPerformed
        
        LoadCBKH();
        int rowSelected = JTB_SP.getSelectedRow();
        if(rowSelected >= 0){
            SanPham_DTO sp = getProductByMaSP(String.valueOf(JTB_SP.getValueAt(rowSelected, 0)));
            eventGiaBanSiLe(rowSelected, sp);
        }
    }//GEN-LAST:event_JCB_HTBanActionPerformed

    private void JCB_NVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCB_NVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JCB_NVActionPerformed

    private void JCB_KHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCB_KHActionPerformed

    }//GEN-LAST:event_JCB_KHActionPerformed

    private void JBtn_BackHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBtn_BackHomeMouseClicked
        JF_Home jF_Home = new JF_Home();
        jF_Home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_JBtn_BackHomeMouseClicked

    private void JCB_DVTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCB_DVTActionPerformed

         int rowSelected = JTB_SP.getSelectedRow(); 
         if(rowSelected >=0){
             SanPham_DTO sp = getProductByMaSP(String.valueOf(JTB_SP.getValueAt(rowSelected, 0)));
             eventGiaBanSiLe(rowSelected, sp);
         }
    }//GEN-LAST:event_JCB_DVTActionPerformed

    private void JBTN_ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTN_ThemActionPerformed
        
        //kiem tra so luong hop le
        int rowSelected = JTB_SP.getSelectedRow();
        if(rowSelected >= 0){
            String maSP = String.valueOf(JTB_SP.getValueAt(rowSelected, 0));
            SanPham_DTO sp = getProductByMaSP(maSP);
            int slTonKho = Integer.parseInt(String.valueOf(JTB_SP.getValueAt(rowSelected, 2)));
            int slDVT_TFSL = Integer.parseInt(JTF_SL.getText());
            int slDVT_TBSP = Integer.parseInt(String.valueOf(JTB_SP.getValueAt(rowSelected, 2)));
            if(checkDVTC_DVTP(String.valueOf(JCB_DVT.getSelectedItem()))){//dvtchinh
                int slQuyDoi = getProductByMaSP(maSP).getQuiDoi();
                int slBan  = slQuyDoi * slDVT_TFSL;

                if(slBan <= slTonKho){
                    //cap nhat sl table SP - GUI
                    int slDVT_TBSP_CapNhat = slDVT_TBSP - slBan;
                    JTB_SP.setValueAt(slDVT_TBSP_CapNhat, rowSelected, 2);
                    String sltQuyDoi_TBSP_CapNhat = tinhTonKhoQuyDoi(sp.getDvtChinh(), sp.getDvtPhu(), slDVT_TBSP_CapNhat, sp.getQuiDoi());
                    JTB_SP.setValueAt(sltQuyDoi_TBSP_CapNhat, rowSelected, 3);
                    addSPVaoTB_CTHD(rowSelected, maSP); //add sp vao tb_CTHD
                }
                else{
                    JOptionPane.showMessageDialog(this, "Số lượng tồn kho không đủ", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                } 
            }
            else{
                if(slDVT_TFSL <= slTonKho){
                    //cap nhat sl table SP - GUI
                    int slDVT_TBSP_CapNhat = slDVT_TBSP - slDVT_TFSL;
                    JTB_SP.setValueAt(slDVT_TBSP_CapNhat, rowSelected, 2);
                    String sltQuyDoi_TBSP_CapNhat = tinhTonKhoQuyDoi(sp.getDvtChinh(), sp.getDvtPhu(), slDVT_TBSP_CapNhat, sp.getQuiDoi());
                    JTB_SP.setValueAt(sltQuyDoi_TBSP_CapNhat, rowSelected, 3);
                    addSPVaoTB_CTHD(rowSelected, maSP); //add sp vao tb_CTHD
                }
                else{
                    JOptionPane.showMessageDialog(this, "Số lượng tồn kho không đủ", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                } 
            }
        }
        else{
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn sản phẩm", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        }
        
        
    }//GEN-LAST:event_JBTN_ThemActionPerformed

    private void JBTN_XoaSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTN_XoaSPActionPerformed
        int rowSelected = JTB_HD.getSelectedRow();
        if(rowSelected >= 0){
            
            String maSP = String.valueOf(JTB_HD.getValueAt(rowSelected, 0));
            SanPham_DTO sp = getProductByMaSP(maSP);
            int slBan_TBHD = Integer.parseInt(String.valueOf(JTB_HD.getValueAt(rowSelected, 4)));
            if(checkDVTC_DVTP(String.valueOf(JTB_HD.getValueAt(rowSelected, 3)))){//dvtchinh
                int slQuyDoi = getProductByMaSP(maSP).getQuiDoi();
                int slBan  = slQuyDoi * slBan_TBHD;
                int rowUpdate_TBSP = layDongTBSP_CapNhatTK(maSP);
                int slTK_TBSP = Integer.parseInt(String.valueOf(JTB_SP.getValueAt(rowUpdate_TBSP, 2)));
                int slTK_TBSP_CapNhat = slBan + slTK_TBSP;
                
                //cap nhat lai table SP
                JTB_SP.setValueAt(slTK_TBSP_CapNhat, rowUpdate_TBSP, 2);
                String slTK_QuyDoi = tinhTonKhoQuyDoi(sp.getDvtChinh(), sp.getDvtPhu(), slTK_TBSP_CapNhat, sp.getQuiDoi());
                JTB_SP.setValueAt(slTK_QuyDoi, rowUpdate_TBSP, 3);
            }
            else{
                int rowUpdate_TBSP = layDongTBSP_CapNhatTK(maSP);
                int slTK_TBSP = Integer.parseInt(String.valueOf(JTB_SP.getValueAt(rowUpdate_TBSP, 2)));
                int slTK_TBSP_CapNhat = slBan_TBHD + slTK_TBSP;
                
                //cap nhat lai table SP
                JTB_SP.setValueAt(slTK_TBSP_CapNhat, rowUpdate_TBSP, 2);
                String slTK_QuyDoi = tinhTonKhoQuyDoi(sp.getDvtChinh(), sp.getDvtPhu(), slTK_TBSP_CapNhat, sp.getQuiDoi());
                JTB_SP.setValueAt(slTK_QuyDoi, rowUpdate_TBSP, 3);
            }
            
            defaultTableModel_HD.removeRow(rowSelected);
            
            if(JTB_HD.getRowCount() == 0){
                JCB_HTBan.setEnabled(true);
            }
        }
        else{
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn sản phẩm cần xóa", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_JBTN_XoaSPActionPerformed

    private void JBTN_XacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTN_XacNhanActionPerformed
        
        int tongDongTBHD = JTB_HD.getRowCount();
        if(tongDongTBHD > 0){
            String ngayLap = dateFormatSQL.format(JDC_Date.getDate());
            NhanVien_DTO nv = (NhanVien_DTO) JCB_NV.getSelectedItem();
            String maNV = nv.getMaNV();
            KhachHang_DTO kh = (KhachHang_DTO) JCB_KH.getSelectedItem();
            String maKH = kh.getMaKH();


            float tongTien = 0;
            for(int i=0; i < tongDongTBHD; i++){
                float thanhTien = Float.parseFloat(String.valueOf(JTB_HD.getValueAt(i, 5)));
                tongTien += thanhTien;
            }

            //tao don hang
            DonHang_DTO dh = new DonHang_DTO();
            dh.setNgayLap(ngayLap);
            dh.setMaNV(maNV);
            dh.setMaKH(maKH);
            dh.setTongTien(tongTien);
            dh_BUS.addDonHang(dh);
            
            int maDH = dh_BUS.getMaDHVuaThem();
            JTF_MaHD.setText("MDH" + String.valueOf(maDH));
            JTF_TongTien.setText(String.format("%.0f", tongTien));
            
            //tao ct don hang
            for(int i = 0; i < tongDongTBHD; i++){
                CT_DonHang_DTO ctdh = new CT_DonHang_DTO();
                ctdh.setMaDH(maDH);
                ctdh.setMaSP(String.valueOf(JTB_HD.getValueAt(i, 0)));
                ctdh.setSoLuong(Integer.parseInt(String.valueOf(JTB_HD.getValueAt(i, 4))));
                String maDVT = getDonViByTenDV_SP(String.valueOf(JTB_HD.getValueAt(i, 3))).getMaDV();
                ctdh.setMaDVT(maDVT);
                ctdh.setThanhTien(Float.parseFloat(String.valueOf(JTB_HD.getValueAt(i, 5))));
                ctDH_BUS.addCTDonHang(ctdh);
            }
            
            JBTN_Them.setEnabled(false);
            JBTN_XoaSP.setEnabled(false);
            JBTN_XacNhan.setEnabled(false);
            JBTN_TaoHDMoi.setEnabled(false);
        }
        else{
            JOptionPane.showMessageDialog(this, "Không thể tạo đơn hàng", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        }
        
        
    }//GEN-LAST:event_JBTN_XacNhanActionPerformed

    private void JBTN_ThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTN_ThanhToanActionPerformed
        //xu ly ton kho
        int slDVT;
        int slBan;
        int tongSLTKCapNhat;
        int tongDongCTHD = JTB_HD.getRowCount();
        for(int i = 0; i < tongDongCTHD; i++){
            String maSP = String.valueOf(JTB_HD.getValueAt(i, 0));
            String tenDVT = String.valueOf(JTB_HD.getValueAt(i, 3));
            SanPham_DTO sp = getProductByMaSP(maSP);
            TonKho_DTO tk = getTonKhoByMaSP(maSP);
            if(checkDVTC_DVTP(tenDVT)){ // dvt chinh
                slDVT = Integer.parseInt(String.valueOf(JTB_HD.getValueAt(i, 4)));
                slBan = slDVT * sp.getQuiDoi();
                tongSLTKCapNhat = tk.getSlTon() - slBan;
                String slTKQuyDoi = tinhTonKhoQuyDoi(sp.getDvtChinh(), sp.getDvtPhu(), tongSLTKCapNhat, sp.getQuiDoi());
                tk.setSlTon(tongSLTKCapNhat);
                tk.setSlTonQuiDoi(slTKQuyDoi);
                tonKho_BUS.UpdateTonKho(tk);
            }
            else {
                slDVT = Integer.parseInt(String.valueOf(JTB_HD.getValueAt(i, 4)));
                tongSLTKCapNhat = tk.getSlTon() - slDVT;
                String slTKQuyDoi = tinhTonKhoQuyDoi(sp.getDvtChinh(), sp.getDvtPhu(), tongSLTKCapNhat, sp.getQuiDoi());
                tk.setSlTon(tongSLTKCapNhat);
                tk.setSlTonQuiDoi(slTKQuyDoi);
                tonKho_BUS.UpdateTonKho(tk);
            }
        }
        
        //load tb sanpham
        JOptionPane.showMessageDialog(this, "Thanh toán thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        LoadTableData(tonKho_BUS.getAllTonKho());
        RefreshJFrame();
    }//GEN-LAST:event_JBTN_ThanhToanActionPerformed

    private void JBTN_TaoHDMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTN_TaoHDMoiActionPerformed
        RefreshJFrame();
    }//GEN-LAST:event_JBTN_TaoHDMoiActionPerformed

    private void JBTN_SearchProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBTN_SearchProductMouseClicked
        if(JTF_SearchProduct.getText().length() > 0){
            String tenSP = JTF_SearchProduct.getText();
 
            defaultTableModel_SP.setRowCount(0);
            List<TonKho_DTO> listTKSearch = tonKho_BUS.SearchTonKho(tenSP);
            LoadTableData(listTKSearch);
        }
        else{
            LoadTableData(tonKho_BUS.getAllTonKho());
        }
    }//GEN-LAST:event_JBTN_SearchProductMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_Sell.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_Sell.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_Sell.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_Sell.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_Sell().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JBTN_SearchProduct;
    private com.k33ptoo.components.KButton JBTN_TaoHDMoi;
    private com.k33ptoo.components.KButton JBTN_ThanhToan;
    private com.k33ptoo.components.KButton JBTN_Them;
    private com.k33ptoo.components.KButton JBTN_XacNhan;
    private com.k33ptoo.components.KButton JBTN_XoaSP;
    private javax.swing.JLabel JBtn_BackHome;
    private javax.swing.JComboBox<DonVi_DTO> JCB_DVT;
    private javax.swing.JComboBox<String> JCB_HTBan;
    private javax.swing.JComboBox<KhachHang_DTO> JCB_KH;
    private javax.swing.JComboBox<NhanVien_DTO> JCB_NV;
    private com.toedter.calendar.JDateChooser JDC_Date;
    private javax.swing.JPanel JF_HoaDon;
    private javax.swing.JPanel JF_ThanhToan;
    private javax.swing.JPanel JP_SanPham;
    private javax.swing.JPanel JP_TTSanPham;
    private javax.swing.JTable JTB_HD;
    private javax.swing.JTable JTB_SP;
    private GUI.JTextFieldCustom JTF_Gia;
    private GUI.JTextFieldCustom JTF_MaHD;
    private GUI.JTextFieldCustom JTF_SL;
    private GUI.JTextFieldCustom JTF_SearchProduct;
    private GUI.JTextFieldCustom JTF_TenSP;
    private GUI.JTextFieldCustom JTF_TongTien;
    private javax.swing.JLabel JTxt_Header2;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
