/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import BUS.NhaCungCap_BUS;
import DTO.NhaCungCap_DTO;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author datsu
 */
public class JF_Supplier extends javax.swing.JFrame {

    /**
     * Creates new form JF_Customer
     */
    
    DefaultTableModel defaultTableModel;
    NhaCungCap_BUS supplier_BUS;
    
    
    public JF_Supplier() {
        initComponents();
        
        
        JTB_Supplier.getTableHeader().setFont(new Font("Segoe UI", Font.PLAIN, 15));
        JTB_Supplier.getTableHeader().setForeground(Color.black);
        JTB_Supplier.getTableHeader().setPreferredSize(new Dimension(1234, 40));
        
        
        JTB_Supplier.getColumnModel().getColumn(0).setPreferredWidth(100);
        JTB_Supplier.getColumnModel().getColumn(0).setMaxWidth(100);
        
        defaultTableModel = (DefaultTableModel) JTB_Supplier.getModel();
        supplier_BUS = new NhaCungCap_BUS();
        
        LoadTableData();
        EventSelectRow();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        JTxt_Header1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        JTF_TenNCC = new GUI.JTextFieldCustom();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JTF_SDTNCC = new GUI.JTextFieldCustom();
        jLabel3 = new javax.swing.JLabel();
        JTF_DiaChiNCC = new GUI.JTextFieldCustom();
        jLabel4 = new javax.swing.JLabel();
        JTF_EmailNCC = new GUI.JTextFieldCustom();
        JTF_MaNCC = new GUI.JTextFieldCustom();
        jLabel6 = new javax.swing.JLabel();
        JTF_SearchSupplier = new GUI.JTextFieldCustom();
        jPanel7 = new javax.swing.JPanel();
        JBtn_AddSupplier = new com.k33ptoo.components.KButton();
        JBtn_UpdateSupplier = new com.k33ptoo.components.KButton();
        JBtn_BackHome = new com.k33ptoo.components.KButton();
        JBtn_DeleteSupplier = new com.k33ptoo.components.KButton();
        JBtn_Refresh = new com.k33ptoo.components.KButton();
        JBtn_SearchSupplier = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTB_Supplier = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel4.setBackground(new java.awt.Color(255, 153, 0));
        jPanel4.setPreferredSize(new java.awt.Dimension(1329, 93));

        JTxt_Header1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        JTxt_Header1.setForeground(new java.awt.Color(255, 255, 255));
        JTxt_Header1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JTxt_Header1.setText("QUẢN LÝ NHÀ CUNG CẤP");
        JTxt_Header1.setPreferredSize(new java.awt.Dimension(1236, 93));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JTxt_Header1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(JTxt_Header1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(245, 245, 245));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel1.setText("Tên nhà cung cấp: ");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel2.setText("Số điện thoại:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel3.setText("Địa chỉ:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel4.setText("Email:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel6.setText("Mã NCC:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(27, 27, 27)
                        .addComponent(JTF_MaNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(31, 31, 31)
                        .addComponent(JTF_DiaChiNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JTF_TenNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JTF_SDTNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(26, 26, 26)
                        .addComponent(JTF_EmailNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(51, 51, 51))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTF_MaNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTF_TenNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(JTF_SDTNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(40, 40, 40)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTF_DiaChiNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(JTF_EmailNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(54, 54, 54))
        );

        jPanel7.setBackground(new java.awt.Color(245, 245, 245));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JBtn_AddSupplier.setText("Thêm");
        JBtn_AddSupplier.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        JBtn_AddSupplier.setkBackGroundColor(new java.awt.Color(255, 102, 0));
        JBtn_AddSupplier.setkBorderRadius(30);
        JBtn_AddSupplier.setkEndColor(new java.awt.Color(255, 153, 0));
        JBtn_AddSupplier.setkHoverEndColor(new java.awt.Color(255, 153, 0));
        JBtn_AddSupplier.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        JBtn_AddSupplier.setkHoverStartColor(new java.awt.Color(255, 102, 0));
        JBtn_AddSupplier.setkSelectedColor(new java.awt.Color(255, 102, 0));
        JBtn_AddSupplier.setkStartColor(new java.awt.Color(255, 153, 0));
        JBtn_AddSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtn_AddSupplierActionPerformed(evt);
            }
        });
        jPanel7.add(JBtn_AddSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 160, -1));

        JBtn_UpdateSupplier.setText("Cập nhật");
        JBtn_UpdateSupplier.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        JBtn_UpdateSupplier.setkBackGroundColor(new java.awt.Color(255, 102, 0));
        JBtn_UpdateSupplier.setkBorderRadius(30);
        JBtn_UpdateSupplier.setkEndColor(new java.awt.Color(255, 153, 0));
        JBtn_UpdateSupplier.setkHoverEndColor(new java.awt.Color(255, 153, 0));
        JBtn_UpdateSupplier.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        JBtn_UpdateSupplier.setkHoverStartColor(new java.awt.Color(255, 102, 0));
        JBtn_UpdateSupplier.setkSelectedColor(new java.awt.Color(255, 102, 0));
        JBtn_UpdateSupplier.setkStartColor(new java.awt.Color(255, 153, 0));
        JBtn_UpdateSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtn_UpdateSupplierActionPerformed(evt);
            }
        });
        jPanel7.add(JBtn_UpdateSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 160, -1));

        JBtn_BackHome.setText("Về trang chủ");
        JBtn_BackHome.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        JBtn_BackHome.setkBackGroundColor(new java.awt.Color(255, 102, 0));
        JBtn_BackHome.setkBorderRadius(30);
        JBtn_BackHome.setkEndColor(new java.awt.Color(51, 153, 255));
        JBtn_BackHome.setkHoverEndColor(new java.awt.Color(51, 102, 255));
        JBtn_BackHome.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        JBtn_BackHome.setkHoverStartColor(new java.awt.Color(51, 102, 255));
        JBtn_BackHome.setkSelectedColor(new java.awt.Color(255, 102, 0));
        JBtn_BackHome.setkStartColor(new java.awt.Color(51, 153, 255));
        JBtn_BackHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtn_BackHomeActionPerformed(evt);
            }
        });
        jPanel7.add(JBtn_BackHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 160, -1));

        JBtn_DeleteSupplier.setText("Xóa");
        JBtn_DeleteSupplier.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        JBtn_DeleteSupplier.setkBackGroundColor(new java.awt.Color(255, 102, 0));
        JBtn_DeleteSupplier.setkBorderRadius(30);
        JBtn_DeleteSupplier.setkEndColor(new java.awt.Color(255, 153, 0));
        JBtn_DeleteSupplier.setkHoverEndColor(new java.awt.Color(255, 153, 0));
        JBtn_DeleteSupplier.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        JBtn_DeleteSupplier.setkHoverStartColor(new java.awt.Color(255, 102, 0));
        JBtn_DeleteSupplier.setkSelectedColor(new java.awt.Color(255, 102, 0));
        JBtn_DeleteSupplier.setkStartColor(new java.awt.Color(255, 153, 0));
        JBtn_DeleteSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtn_DeleteSupplierActionPerformed(evt);
            }
        });
        jPanel7.add(JBtn_DeleteSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 160, -1));

        JBtn_Refresh.setText("Làm mới");
        JBtn_Refresh.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        JBtn_Refresh.setkBackGroundColor(new java.awt.Color(255, 102, 0));
        JBtn_Refresh.setkBorderRadius(30);
        JBtn_Refresh.setkEndColor(new java.awt.Color(255, 153, 0));
        JBtn_Refresh.setkHoverEndColor(new java.awt.Color(255, 153, 0));
        JBtn_Refresh.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        JBtn_Refresh.setkHoverStartColor(new java.awt.Color(255, 102, 0));
        JBtn_Refresh.setkSelectedColor(new java.awt.Color(255, 102, 0));
        JBtn_Refresh.setkStartColor(new java.awt.Color(255, 153, 0));
        JBtn_Refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtn_RefreshActionPerformed(evt);
            }
        });
        jPanel7.add(JBtn_Refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 160, -1));

        JBtn_SearchSupplier.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JBtn_SearchSupplier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon_search.png"))); // NOI18N
        JBtn_SearchSupplier.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JBtn_SearchSupplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JBtn_SearchSupplierMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(JTF_SearchSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 1159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JBtn_SearchSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JTF_SearchSupplier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JBtn_SearchSupplier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new java.awt.CardLayout());

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        JTB_Supplier.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        JTB_Supplier.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MNCC", "Tên nhà cung cấp", "Số điện thoại", "Địa chỉ", "Email"
            }
        ));
        JTB_Supplier.setGridColor(new java.awt.Color(204, 204, 204));
        JTB_Supplier.setRowHeight(40);
        JTB_Supplier.setSelectionBackground(new java.awt.Color(153, 153, 153));
        JTB_Supplier.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        JTB_Supplier.setShowGrid(false);
        jScrollPane1.setViewportView(JTB_Supplier);

        jPanel6.add(jScrollPane1, "card2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 1239, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, "card2");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    
     private void LoadTableData(){ 
        
        defaultTableModel.setRowCount(0);
        List<NhaCungCap_DTO> listNCC = supplier_BUS.getAllSupplier();
        for(NhaCungCap_DTO ncc : listNCC){
            defaultTableModel.addRow(new Object[] {ncc.getMaNCC(), ncc.getTenNCC(), ncc.getSdtNCC(), ncc.getDiaChiNCC(), ncc.getEmailNCC()});
        }
    }
     
    private void EventSelectRow(){
        ListSelectionModel listSelectionModel = JTB_Supplier.getSelectionModel();
        listSelectionModel.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                int row = JTB_Supplier.getSelectedRow();
                
                if(row >= 0){
                    String maNCC = String.valueOf(JTB_Supplier.getValueAt(row, 0));
                    String tenNCC = String.valueOf(JTB_Supplier.getValueAt(row, 1));
                    String sdtNCC = String.valueOf(JTB_Supplier.getValueAt(row, 2));
                    String diaChiNCC = String.valueOf(JTB_Supplier.getValueAt(row, 3));
                    String emailNCC = String.valueOf(JTB_Supplier.getValueAt(row, 4));

                    JTF_MaNCC.setText(maNCC);
                    JTF_TenNCC.setText(tenNCC);
                    JTF_SDTNCC.setText(sdtNCC);
                    JTF_DiaChiNCC.setText(diaChiNCC);
                    JTF_EmailNCC.setText(emailNCC);

                    JTF_MaNCC.setEnabled(false);
                    JBtn_AddSupplier.setEnabled(false);
                }
            }
        });
    }
    
    private void ClearTextFiled(){
        JTF_MaNCC.setText("");
        JTF_TenNCC.setText("");
        JTF_SDTNCC.setText("");
        JTF_DiaChiNCC.setText("");
        JTF_EmailNCC.setText("");
    }
    
    private NhaCungCap_DTO getDataSupplierFromGUI(){
        
        String maNCC = JTF_MaNCC.getText();
        String tenNCC = JTF_TenNCC.getText();
        String sdtNCC = JTF_SDTNCC.getText();
        String diaChiNCC = JTF_DiaChiNCC.getText();
        String emailNCC = JTF_EmailNCC.getText();
        
        NhaCungCap_DTO ncc = new NhaCungCap_DTO();
        ncc.setMaNCC(maNCC);
        ncc.setTenNCC(tenNCC);
        ncc.setSdtNCC(sdtNCC);
        ncc.setDiaChiNCC(diaChiNCC);
        ncc.setEmailNCC(emailNCC);
        
        return ncc;
    }
     
    private void JBtn_BackHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtn_BackHomeActionPerformed
        JF_Home jF_Home = new JF_Home();
        jF_Home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_JBtn_BackHomeActionPerformed

    private void JBtn_RefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtn_RefreshActionPerformed
       ClearTextFiled();
       LoadTableData();
       JTF_MaNCC.setEnabled(true);
       JBtn_AddSupplier.setEnabled(true);
    }//GEN-LAST:event_JBtn_RefreshActionPerformed

    private void JBtn_AddSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtn_AddSupplierActionPerformed
        
        if(JTF_MaNCC.getText().compareTo("") != 0 && JTF_TenNCC.getText().compareTo("") != 0){
            supplier_BUS.AddSupplier(getDataSupplierFromGUI());
            LoadTableData();
            JOptionPane.showMessageDialog(this, "Thêm thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            ClearTextFiled();
        }
        else{
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập thông tin nhà cung cấp", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_JBtn_AddSupplierActionPerformed

    private void JBtn_UpdateSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtn_UpdateSupplierActionPerformed
        int row = JTB_Supplier.getSelectedRow();
            
            if(row >= 0){
                defaultTableModel.setRowCount(0);
                supplier_BUS.UpdateSupplier(getDataSupplierFromGUI());

                LoadTableData();
                JOptionPane.showMessageDialog(this, "Sửa thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                ClearTextFiled();
                JTF_MaNCC.setEnabled(true);
                JBtn_AddSupplier.setEnabled(true);
            }
            else{
                JOptionPane.showMessageDialog(this, "Bạn chưa chọn nhà cung cấp cần sửa", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            }
    }//GEN-LAST:event_JBtn_UpdateSupplierActionPerformed

    private void JBtn_DeleteSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtn_DeleteSupplierActionPerformed
        int row = JTB_Supplier.getSelectedRow();
        
        if(row >= 0){
            int confirm = JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa không?");
        
            if(confirm == JOptionPane.YES_OPTION){
                String maNCC = JTF_MaNCC.getText();
                supplier_BUS.DeleteSupplier(maNCC);
                
                LoadTableData();
                JOptionPane.showMessageDialog(this, "Xóa thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                ClearTextFiled();  
            }
        }
        else{
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn nhà cung cấp cần xóa", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_JBtn_DeleteSupplierActionPerformed

    private void JBtn_SearchSupplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBtn_SearchSupplierMouseClicked
        if(JTF_SearchSupplier.getText().length() > 0){
            String tenNCC = JTF_SearchSupplier.getText();
 
            defaultTableModel.setRowCount(0);
            List<NhaCungCap_DTO> listNCC = supplier_BUS.SearchSupplier(tenNCC);
            for(NhaCungCap_DTO ncc : listNCC){
                defaultTableModel.addRow(new Object[] {ncc.getMaNCC(), ncc.getTenNCC(), ncc.getSdtNCC(), ncc.getDiaChiNCC(), ncc.getEmailNCC()});
            }
        }
        else{
            LoadTableData();
        }
    }//GEN-LAST:event_JBtn_SearchSupplierMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_Supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_Supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_Supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_Supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_Supplier().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KButton JBtn_AddSupplier;
    private com.k33ptoo.components.KButton JBtn_BackHome;
    private com.k33ptoo.components.KButton JBtn_DeleteSupplier;
    private com.k33ptoo.components.KButton JBtn_Refresh;
    private javax.swing.JLabel JBtn_SearchSupplier;
    private com.k33ptoo.components.KButton JBtn_UpdateSupplier;
    private javax.swing.JTable JTB_Supplier;
    private GUI.JTextFieldCustom JTF_DiaChiNCC;
    private GUI.JTextFieldCustom JTF_EmailNCC;
    private GUI.JTextFieldCustom JTF_MaNCC;
    private GUI.JTextFieldCustom JTF_SDTNCC;
    private GUI.JTextFieldCustom JTF_SearchSupplier;
    private GUI.JTextFieldCustom JTF_TenNCC;
    private javax.swing.JLabel JTxt_Header1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
