/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import BUS.SanPham_BUS;
import BUS.TonKho_BUS;
import DTO.SanPham_DTO;
import DTO.TonKho_DTO;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.util.List;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author datsu
 */
public class JF_WareHouse extends javax.swing.JFrame {

    /**
     * Creates new form JF_Customer
     */
    
    DefaultTableModel defaultTableModel;
    TonKho_BUS tk_BUS;
    SanPham_BUS product_BUS;
    List<SanPham_DTO> list_Product;

    
    
    public JF_WareHouse() {
        initComponents();
        
        
        JTB_WareHouse.getTableHeader().setFont(new Font("Segoe UI", Font.PLAIN, 15));
        JTB_WareHouse.getTableHeader().setForeground(Color.black);
        JTB_WareHouse.getTableHeader().setPreferredSize(new Dimension(1234, 40));
        JTB_WareHouse.getColumnModel().getColumn(0).setPreferredWidth(100);
        JTB_WareHouse.getColumnModel().getColumn(0).setMaxWidth(100);
        
        tk_BUS = new TonKho_BUS();
        product_BUS = new SanPham_BUS();
        defaultTableModel = (DefaultTableModel) JTB_WareHouse.getModel();
        
        LoadDataTableTonKho(tk_BUS.getAllTonKho());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        JTxt_Header1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        JTF_SearchWareHouse = new GUI.JTextFieldCustom();
        JBTN_SearchWareHouse = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTB_WareHouse = new javax.swing.JTable();
        JBtn_BackHome = new com.k33ptoo.components.KButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel4.setBackground(new java.awt.Color(255, 153, 0));
        jPanel4.setPreferredSize(new java.awt.Dimension(1329, 93));

        JTxt_Header1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        JTxt_Header1.setForeground(new java.awt.Color(255, 255, 255));
        JTxt_Header1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JTxt_Header1.setText("TỒN KHO");
        JTxt_Header1.setPreferredSize(new java.awt.Dimension(1236, 93));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JTxt_Header1, javax.swing.GroupLayout.DEFAULT_SIZE, 1027, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(JTxt_Header1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(245, 245, 245));

        JBTN_SearchWareHouse.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JBTN_SearchWareHouse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon_search.png"))); // NOI18N
        JBTN_SearchWareHouse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JBTN_SearchWareHouse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JBTN_SearchWareHouseMouseClicked(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        JTB_WareHouse.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        JTB_WareHouse.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã SP", "Tên sản phẩm", "SL tồn", "SL tồn (Quy đổi)"
            }
        ));
        JTB_WareHouse.setGridColor(new java.awt.Color(204, 204, 204));
        JTB_WareHouse.setRowHeight(40);
        JTB_WareHouse.setSelectionBackground(new java.awt.Color(153, 153, 153));
        JTB_WareHouse.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        JTB_WareHouse.setShowGrid(false);
        jScrollPane1.setViewportView(JTB_WareHouse);

        JBtn_BackHome.setText("Về trang chủ");
        JBtn_BackHome.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        JBtn_BackHome.setkBackGroundColor(new java.awt.Color(255, 102, 0));
        JBtn_BackHome.setkBorderRadius(30);
        JBtn_BackHome.setkEndColor(new java.awt.Color(51, 153, 255));
        JBtn_BackHome.setkHoverEndColor(new java.awt.Color(51, 102, 255));
        JBtn_BackHome.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        JBtn_BackHome.setkHoverStartColor(new java.awt.Color(51, 102, 255));
        JBtn_BackHome.setkSelectedColor(new java.awt.Color(255, 102, 0));
        JBtn_BackHome.setkStartColor(new java.awt.Color(51, 153, 255));
        JBtn_BackHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtn_BackHomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JTF_SearchWareHouse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JBTN_SearchWareHouse, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(JBtn_BackHome, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addComponent(jScrollPane1)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JTF_SearchWareHouse, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBtn_BackHome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JBTN_SearchWareHouse, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 1027, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, "card2");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JBtn_BackHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtn_BackHomeActionPerformed
        JF_Home jF_Home = new JF_Home();
        jF_Home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_JBtn_BackHomeActionPerformed

    private void JBTN_SearchWareHouseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBTN_SearchWareHouseMouseClicked
        if(JTF_SearchWareHouse.getText().length() > 0){
            String tenSP = JTF_SearchWareHouse.getText();
 
            defaultTableModel.setRowCount(0);
            List<TonKho_DTO> listTKSearch = tk_BUS.SearchTonKho(tenSP);
            LoadDataTableTonKho(listTKSearch);
        }
        else{
            LoadDataTableTonKho(tk_BUS.getAllTonKho());
        }
    }//GEN-LAST:event_JBTN_SearchWareHouseMouseClicked

    private void LoadDataTableTonKho(List<TonKho_DTO> list_TK){
        defaultTableModel.setRowCount(0);
        for(TonKho_DTO tk : list_TK){
            SanPham_DTO sp = getProductByMaSP(tk.getMaSP());
            defaultTableModel.addRow(new Object[] {tk.getMaSP(), sp.getTenSP(), tk.getSlTon(), tk.getSlTonQuiDoi()});
        }
    }
    
    private SanPham_DTO getProductByMaSP(String maSP){
        list_Product = product_BUS.getAllProduct();
        for(SanPham_DTO sp : list_Product){
            if(sp.getMaSP().compareTo(maSP) == 0){
                return sp;
            }
        }
        return null;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_WareHouse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_WareHouse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_WareHouse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_WareHouse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_WareHouse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JBTN_SearchWareHouse;
    private com.k33ptoo.components.KButton JBtn_BackHome;
    private javax.swing.JTable JTB_WareHouse;
    private GUI.JTextFieldCustom JTF_SearchWareHouse;
    private javax.swing.JLabel JTxt_Header1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
